### ISSUE TITLE
Feature Request: Reminder tokens for unassigned roles

### ISSUE THREAD

**Issue by madformadrigals** [bra1n/townsquare#101]
**Is your feature request related to a problem? Please describe.**
Not really, just something I'd like to be able to do.

**Describe the solution you'd like**
As a player, I would love to be able to assign reminder tokens for characters that I have not assigned to a player. For example, when a widow is in play, I'd like to be able to assign "seen widow" to a player without arbitrarily marking someone as the widow.

**Describe alternatives you've considered**
Perhaps it could be an option in the settings, as it might be overwhelming for some players to have constant access to all reminder tokens?

**Additional context**
N/A.

**Comment by bra1n** [comment]
This is already possible in a way, by assigning roles to the "bluff"/"other characters" window in the bottom left corner of the grimoire. Any characters you assign there will also populate the list of reminders. Does that help?

**Comment by davotronic5000** [comment]
This is possibly something we could do in a similar way to the other travelers on the role modal if it is useful to have access to the tokens, without cluttering the UI.

**Comment by bra1n** [comment]
The Widow reminder has been made global now, so it should always be selectable when the Widow is on the script. With that and the workaround of assigning roles to the "other characters" window, I'm going to close this ticket for now.
