### ISSUE TITLE
Feature Request: Night Phase player names near roles

### ISSUE THREAD

**Issue by magroader** [bra1n/townsquare#102]
**Is your feature request related to a problem? Please describe.**
Running night time is tricky, especially with a lot of people present, because I have to look around the circle and find incrementing numbers.

I can use the Night Order sheet instead, like I would in real life, but it doesn't actually tell me who is who, so I have to keep closing and reopening the night sheet, which is tedious.

**Describe the solution you'd like**
On the Night Phase screen, put the name of the player(s) in each role, with a different coloration/icon if they are dead.

<img width="942" alt="nightOrder" src="https://user-images.githubusercontent.com/151634/105611736-0cb2a580-5d85-11eb-9066-44fe1eded6c6.png">

**Comment by bra1n** [comment]
Good idea! I'll add it.

**Comment by bra1n** [comment]
Added with 2.5.0

**Comment by magroader** [comment]
This looks great. Some comments from my Storyteller friends:

> holy butts, that looks so cool!

> Nice! That was why I didn’t use this screen at night

**Comment by bra1n** [comment]
Haha, thanks for the feedback! 😄
