### ISSUE TITLE
Feature Request: Tooltips on Night Order

### ISSUE THREAD

**Issue by magroader** [bra1n/townsquare#104]
**Is your feature request related to a problem? Please describe.**
I haven't tried it yet, but now that the Night Phase has names on it (looks awesome!!), it seems like it is likely to be my go-to screen when night hits. As such, it seems like it could use the night info in a tooltip - the info you normally see when you mouse over the little bubbles to the sides of the seat circles.

**Describe the solution you'd like**
When mousing over an area on the night sheet, show the first/other night tooltip.

![image](https://user-images.githubusercontent.com/151634/105760216-75358a00-5f1f-11eb-9257-6a530ef67ac3.png)

**Comment by bra1n** [comment]
Alright, that's a bit more work, but definitely doable. I'll see when I have time for this. :-)

**Comment by bra1n** [comment]
Added!
