### ISSUE TITLE
Feature Request: Night order names - add death indicator

### ISSUE THREAD

**Issue by magroader** [bra1n/townsquare#106]
**Is your feature request related to a problem? Please describe.**
The new Night Order has names of players on it. But it has no indication of whether those players are dead or not. This would be useful because most roles do not do anything if the person is dead.

**Describe the solution you'd like**
A small skull / shroud icon next to dead players, or a small heart icon next to alive players. Or both!

![image](https://user-images.githubusercontent.com/151634/105777111-d0737680-5f37-11eb-83b2-84afbd629d61.png)

**Comment by bra1n** [comment]
Good idea, I think I'll also add this to the reference sheet player list. 👍
