### ISSUE TITLE
Feature Request: Custom Fabled

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#110]
**Is your feature request related to a problem? Please describe.**
Homebrew scripts currently can add custom character types, custom characters, script icon etc, but does not support adding custom Fabled.
Custom Fabled can allow script makers to describe their homebrew rules in a more convenient manner, or just to allow players to try out various Fabled ideas that are floating around.

**Describe the solution you'd like**
When a custom script is uploaded, characters which have the "team": "fabled" should be added to active fabled list.

**Comment by bra1n** [comment]
I think the idea has merit, but it is a bit more complicated, because Fabled are completely separated from player characters. I'll put it on the todo list, but don't expect it to be added very soon.
