### ISSUE TITLE
Bug: Toymaker breaks Night Order Modal

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#112]
**Describe the bug**
Having Toymaker in play disallows players from loading the Night Order Modal

**To Reproduce**
1. Load any script
2. Add a Toymaker Fabled character
3. Press `N` to attempt to load the Night Order Modal

**Expected behavior**
Toymaker should either be ignored in Night Order Modal or it should appear somewhere in the Night Order

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Developer edition
 - Version 86.0b4 (64-bit)

**Additional context**
Problem reported by multiple if not all players in the game

**Comment by bra1n** [comment]
Thanks for the bug report, I'll fix it ASAP!

**Comment by bra1n** [comment]
Fixed.
