### ISSUE TITLE
Feature Request: Auto-Reveal All Characters

### ISSUE THREAD

**Issue by bigheadzach** [bra1n/townsquare#116]
"Show Character" updates seated players' character tokens (overwrites any local changes), but doesn't do anything with tokens not belonging to the individual seated players.

A "Reveal Grimoire" or "Show All Characters" should essentially force-update all player logins to match whatever state the Host Grimoire is in, obviously locked behind a "This will spoil the game and should only be used once it has ended. Do you really want to do this?" confirmation popup, perhaps even requiring the host to type a word out instead of just clicking OK.

**Comment by bra1n** [comment]
Not a bad idea, but also something that is usually solved by sharing the screen or just taking a screenshot. I'll think about it, but it would be very low on the priority list.

**Comment by nicfreeman1209** [comment]
Might be better to have 'reveal single character' that the ST can use one by one whilst doing a verbal reveal?

**Comment by bra1n** [comment]
That would actually be *more* work, so I'd go with the initial idea. ;-)

**Comment by nicfreeman1209** [comment]
Ahh, but I might try and do it ;) I'll wait and see if the socket part is ok on my current pr though.

**Comment by nicfreeman1209** [comment]
I tried some code for this locally. It seems cleanest to add a revealPlayer function that sends a direct message similarly to distributeRoles (with just one player/role as content), but currently that won't show up when the target circle on the client grimoire has already been assigned a role.  

So imo this is linked to https://github.com/bra1n/townsquare/issues/143. I am not keen on giving ST permission to overwrite players own notes, but it could be the best option for these two cases, and then there is the question of what to do with reminder 'character' tokens (drunk, marionette, etc) ... ?

**Comment by bra1n** [comment]
Implemented in the official app.
