### ISSUE TITLE
Feature Request: Hide Players in reference when in Town Square mode

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#119]
**Is your feature request related to a problem? Please describe.**
Especially when playing with custom or homebrew scripts, players often send their reference to others, but as a player or as an ST, if you send your reference, you leak your Grimoire too. It is fine if it's in Grimoire mode, because reference is transparent anyway, but in Town Square mode, I think it's better if you cannot see the players' roles.

**Describe the solution you'd like**
Hide Players column in reference & night order when in Town Square mode

**Describe alternatives you've considered**
Status quo has worked for a long time
Optionally, we could have a toggle, just like night order numbers.

**Additional context**
Games have been ruined due to ST incompetence, but I think UI is partly at fault

**Comment by bra1n** [comment]
Good idea!

**Comment by bra1n** [comment]
added with v2.9.1
