### ISSUE TITLE
You cannot unassign a traveller role from a character

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#12]
If you've joined a session and set a character to be a traveller, you can't unassign the role from them. Obviously in the normal use case you know they're a traveller but if you misclick assigning a role to someone and select a traveller then they're just as that until you leave the session and gain the ability to remove characters.

**Comment by bra1n** [comment]
Good catch, I'll have to hide traveler roles from role selection when in spectator mode.

**Comment by bra1n** [comment]
Fixed with https://github.com/bra1n/townsquare/commit/505593d1c6b5ea44f6609c6f13a00b6e3196943a
