### ISSUE TITLE
Feature Request: Display currently viewable number of nomination log entries to all players.  

### ISSUE THREAD

**Issue by langford** [bra1n/townsquare#124]
**Is your feature request related to a problem? Please describe.**
When players who have read the basic rules/only played in person online, they may be surprised about the existence of a voting log. 

Players who may wish to have a limited voting log do not have an easy way to check the ST is clearing it often enough

**Describe the solution you'd like**
Add a link to use the already present voting log toggle that also displays the count of entries in the voting log. See https://github.com/bra1n/townsquare/issues/121#issuecomment-792313413 for more in the comments

**Describe alternatives you've considered**
I considered multiple ways to show this formatted text and multiple locations. I considered moving the version text, using the upper left corner to display the text, or to put it in the middle in a live log fashion. 

**Additional context**
https://github.com/bra1n/townsquare/issues/121#issuecomment-792313413 was about disabling the voting log. Several players mentioned a third way of having a limited log. I thought my new player suprise could have been prevented by showing the changing log list in game. @bra1n said this would need to be a second PR, so I am making this issue to allow easy discussion of the PR and alternatives. 

Here is what the log indicator currently looks like in the PR I'm working on. Happy to move it, etc. 

<img width="1231" alt="Screen Shot 2021-03-08 at 5 46 19 PM" src="https://user-images.githubusercontent.com/271309/110392960-c618c200-8037-11eb-9a49-5c411a954fb6.png">

**Comment by langford** [comment]
Pr #125 is a candidate solution to this.

**Comment by bra1n** [comment]
I'm still a bit undecided on whether this should be shown so prominently...
In any case, I'd suggest you find a suitable icon to use instead of the lengthy text.

**Comment by langford** [comment]
<img width="1127" alt="Screen Shot 2021-03-11 at 3 06 17 PM" src="https://user-images.githubusercontent.com/271309/110847812-60b51300-827b-11eb-85a7-ce813fc17f33.png">

I forgot to re-set my origin on the icon-based alternative. I accidentally pushed onto this PR a few times as a result. Apologies about the noise. 

Here is a picture of the PR now, it's just the book with the skull and crossbones, no text.
