### ISSUE TITLE
Swap roles button

### ISSUE THREAD

**Issue by david-urvoy** [bra1n/townsquare#128]
**Is your feature request related to a problem? Please describe.**
Since we use Townsquare a lot, some of our game masters have found it cumbersome to swap roles between players, even though it seems like a frequent action.
Right now, the only way to do this is to manually reassign both roles to each player.

**Describe the solution you'd like**
 Since a `swap seats` button exists, it may make sense to add the same kind of button, just below.

**Describe alternatives you've considered**
The underlying action modal may get bigger and bigger if you keep adding features to it, so creating some kind of "submodal" might become useful in the future, or any other solution. But it seems fine for now.

**Additional context**
I have written some more details for this feature, in the [`Discussions` area](https://github.com/bra1n/townsquare/discussions/118) (I thought the discussions related to new features were there), and as explained, I already implemented this feature on our fork of the project (I included a picture to show the result). So if this feature is accepted, I can already open a pull request.

**Comment by bra1n** [comment]
I added a reply to the discussion - I didn't get a notification when you submitted it so I wasn't aware of it until now.

**Comment by david-urvoy** [comment]
Okay, let's continue the converstation here since it is your usual way to prepare features ?

I agree with your remark with the ever growing player menu, as it is something that I emphasized in the "considered alternatives". If you want an other modal to reduce the size of the existing one, I guess it could be done by only having a `Swap` button, which opens a new modal, either beside the principal one (like in the good old windows Start menu), or in place of it, with a back button to cancel the action. This other modal would have `Swap seats`, `Swap roles` and any other upcoming swap actions.

I would like to complete your remark stating that you thought of two BOTC roles that could swap roles between players. This is a valid need for this feature, but it has most notably been requested by our game masters for the game setup phase. Sometimes, the game masters know the game composition they want to make, but they don't assign roles randomly (beginner players may start with "easier" roles, or we don't want players to play with the same role than a few previous games) and they need to vizualise the game board and make changes easily. Swapping seats between players is important as some roles get impacted from positioning, but swapping roles would be important as well to help the roles distribution.

**Comment by bra1n** [comment]
This is probably still too niche for becoming a part of the app, but rest assured that roles that *need* special features (like Snake Charmer or Barber), will get their own tools at some point in the future. This would include the ability for the ST to swap to player roles when there's a Barber or SC on the script.
