### ISSUE TITLE
Bug: Remove Characters option is removing pronouns from players.

### ISSUE THREAD

**Issue by davotronic5000** [bra1n/townsquare#129]
**Describe the bug**
Player pronouns are cleared for all users when a Storyteller chooses to remove all characters from the menu.

**To Reproduce**
1. Set a pronoun for multiple players
2. Click on "Remove All" in the character menu

**Expected behavior**
Only the charachters in the local grimoire should be affected by the remove all characters option, it should not affect pronouns or other players grimoires

**Comment by bra1n** [comment]
Good find, thanks for fixing it! 😃
