### ISSUE TITLE
Bug: The votes of nominated players do not count in the preview voting screen

### ISSUE THREAD

**Issue by JoshCode** [bra1n/townsquare#131]
**Describe the bug**
The votes of players that are nominated do not count in the preview voting screen, before the Storyteller has started the vote. They do count as normal once the minute hand has arrived at their position.

**To Reproduce**
1. Go to https://clocktower.online and host a new game
2. Add five players
3. Have one player (player 1) join in any seat (in my case, I opened a Vivaldi tab and incognito tab, an Edge tab and Edge InPrivate tab, and a Firefox Private tab to fill all 5 seats, with a Firefox tab hosting the game)
4. As the Storyteller, mark that _player 2_ nominates _player 1_
5. Player 1 raises their hand
6. Still in the pre-start voting screen, the count of the votes is still 0 even though player 1 has their hand raised. (In my screenshots, the count is 4 with all 5 players having their hand raised)

**Expected behavior**
The count of the votes should be 1, because player 1 has their hand raised. (Or in my screenshots, the count should be 5)

**Screenshots**
***View from the Storyteller***
![image](https://user-images.githubusercontent.com/6254388/111030209-51f86880-8401-11eb-8aa0-5da18bbeca21.png)

***View from the nominee***
![Screenshot 2021-03-13 134124](https://user-images.githubusercontent.com/6254388/111030330-e236ad80-8401-11eb-897e-8632fb04e38d.png)

***View from another player***
![Screenshot_2021-03-13 Blood on the Clocktower Town Square](https://user-images.githubusercontent.com/6254388/111030331-e4990780-8401-11eb-91d6-ecbfe71c3b1d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Education
 - Browser: Firefox (Storyteller), but verified the bug is present on Vivaldi (3.7.2218.29) and Chromium Edge (89.0.774.50) (as players)
 - Version: Firefox 87.0b9

**Comment by bra1n** [comment]
confirmed and fixed
