### ISSUE TITLE
Bug: Poppy Grower appears after Minion Info in the Night Order

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#139]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3476614/112078356-2d755c80-8b76-11eb-9950-fdb6fcddc9a1.png)

**Expected behavior**
Poppy Grower should appear before Minion Info (since you need to evaluate Poppy Grower before deciding Minion Info)

**Comment by bra1n** [comment]
@eddgabriel was faster 😃
