### ISSUE TITLE
Feature Request: Remove all characters hotkey or prompt when storyteller sends characters

### ISSUE THREAD

**Issue by ZekeMiller** [bra1n/townsquare#143]
I often forget to clear notes from previous games and am not sure if I have the same character or if new roles haven't been dealt. It'd be nice if there was a quick way to clear notes, or if the send characters action would prompt players to clear their grimoire before populating their character, which removes the ambiguity.

**Comment by bra1n** [comment]
This has been brought up before and I'd like to add something like that in the near future. I'm just not sure yet how it would work best... maybe it will auto-clear all characters when the ST sends out the roles...

**Comment by bra1n** [comment]
Fixed in the official app.
