### ISSUE TITLE
Feature Request: Improved Storyteller migration

### ISSUE THREAD

**Issue by magroader** [bra1n/townsquare#146]
**Is your feature request related to a problem? Please describe.**
We often play 2-3 games in a night, and we change who is Storyteller. The switchover is always awkward due to the "There's already a Storyteller in this game" error message.

Instead, we always end up hosting a new room with a new name, and have everyone leave the first game and join the second game. This is awkward!

**Describe the solution you'd like**
The Storyteller should be able to promote another player to be Storyteller, taking over their seat.

**Describe alternatives you've considered**
Hosting a game somehow allows you to take over for the existing host.

**Comment by bra1n** [comment]
Thanks for the ticket, Colin! Unfortunately, the way the backend is built there can only ever be one player connected as the storyteller, so adding a feature that forces a switch there would be pretty convoluted. I'd suggest you just let the original ST leave the session (press "J") and then have the new ST leave their player-session ("J") and then join as a host ("H") - this should keep everything as it is and allow the old ST to rejoin as a player.
