### ISSUE TITLE
Feature Request: Allow players to assign multiple roles and/or generic Demon/Minion

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#15]
As a player it's quite useful to track information in the grimoire but you're forced to assign one role to a player or to assign Demon/Minion to someone since you might not know which Minion/Demon there was.

**Comment by bra1n** [comment]
I plan to add a textbox for taking notes next to each player at some point, that would be a good place to write down suspected roles. Anything more than that would probably be very complicated. When I'm sure someone is evil but I don't know their role yet, I usually just give them an "evil" reminder token.

**Comment by bra1n** [comment]
This can be closed, both the bluff space as well as the custom notes can be used to assign multiple roles or a "general" demon. I also plan to add Fabled and a global "character token space" at some point.
