### ISSUE TITLE
Bug: Mouse over hitbox for reminder token + can cause flicker

### ISSUE THREAD

**Issue by magroader** [bra1n/townsquare#153]
**Describe the bug**
When the mouse is on the edge of the hitbox for showing the reminder token + button, it can cause the + button to appear and disappear rapidly.

**To Reproduce**
(NOTE: This happens with any number of players in any position, but these reproduction steps are very simple.)

1. Start with no players
2. Add one player
3. Put the mouse in the center of the town
4. Slowly move the mouse upward toward the player
5. Stop when the + icon starts rapidly appearing and disappearing

**Expected behavior**
When the mouse approaches close enough to a player, the + button should appear and stay there.

**Screenshots**
Happens approximately here:
![image](https://user-images.githubusercontent.com/151634/115753620-66694280-a369-11eb-9930-333f0db69c33.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)

**Additional context**
I suspect the hitbox for the icon appearing should be large enough to encompass the full animation of the + button. Either that or the hitbox should be located in the final resting place of the + button, not where it animates from.

**Comment by bra1n** [comment]
Thanks for the bug report, I'll look into it. 😃

**Comment by bra1n** [comment]
Fixed by @nathansferguson
