### ISSUE TITLE
Feature Request: Show dividing line on voting screen if game has switched to night/day since prior vote

### ISSUE THREAD

**Issue by magroader** [bra1n/townsquare#154]
(I may have already suggested this before, but I didn't find it in the issues list. If I did, apologies!)

**Is your feature request related to a problem? Please describe.**

We like using the voting history feature, but it's sometimes difficult to tell on which day nominations happen, especially when there is a highly aggressive day of nominations.

Since the website already supports day/night switching, I propose that this switch be used to indicate to the site that a new day of voting has begun.

**Describe the solution you'd like**

When displaying the voting history, insert a line between any nominations where a switch to day/night occurred.

![image](https://user-images.githubusercontent.com/151634/115754117-e4c5e480-a369-11eb-9d85-5a74a8211096.png)

The site doesn't need to track which day it is currently or anything, it would just be nice to have the switch from day/night provide a hint on how to better display the nomination history view.

**Additional context**
It would also be nice if the site could track what day/night it is during a game, and display that for everyone to see (NIGHT 3, DAY 4), but that's not necessary for this feature.

**Comment by bra1n** [comment]
I guess switching from night to day could create an entry in the vote history, but there is not going to be any day or night counter beyond that, because that would require actual game logic to be implemented.

**Comment by bra1n** [comment]
I've added this to the wishlist of the official app, but it won't be a part of this one.
