### ISSUE TITLE
Feature Request: Organizing the selection of roles for when players click the grey circles

### ISSUE THREAD

**Issue by ryan161514131211** [bra1n/townsquare#156]
For players, when clicking on the grey circle to select a role for another player, all the roles come up in two lines, unseparated.  It often takes time to find the role to assign to the player - they are not separated or sorted in a way that is easy to find them, especially when players always play different scripts.

It would be very helpful if they were either:
a) alphabetical OR
b) sorted by character type on separate lines OR
c) in a format somewhat similar to how a Host Storyteller picks/assigns roles

Thank you!!

**Comment by bra1n** [comment]
Well, they *are* sorted in the script order, so it's not like they are random... But I guess the list could be improved a bit, visually.

**Comment by bra1n** [comment]
This will be implemented in the official app. :-)
