### ISSUE TITLE
crash if player list is modified during voting

### ISSUE THREAD

**Issue by nicfreeman1209** [bra1n/townsquare#164]
To reproduce: start a nomination, run the vote, the while the vote is in progress e.g. remove a player who hasn't yet had the chance to vote.

If you do it before running the vote, the vote graphics go wrong but (iirc) there isn't a crash (yet).

Afaics its simplest to lock changes to the player list during nominations/voting.

**Comment by bra1n** [comment]
Thanks, I'll look into it!
