### ISSUE TITLE
Bug: Grandmother (and possibly others) have image data in transparent portions of the icons

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#176]
**Describe the bug**

**To Reproduce**
1. Remove transparency for all pixels in an icon

**Expected behavior**
Icons with transparency should have consistent and remove

**Screenshots**
Transparency removed
![image](https://user-images.githubusercontent.com/46909274/119896067-2fc5af80-bf47-11eb-9d7b-3d3e55e85035.png)
Original
![image](https://user-images.githubusercontent.com/46909274/119896087-35bb9080-bf47-11eb-85e3-78e98e91b2d9.png)

**Additional context**
The reason this is relevant is because some automatic tools (for example zealous cropping) will interpret those empty areas as meaningful.

**Comment by bra1n** [comment]
Okay, I see that there are some extra pixels in the bottom left corner, but the main purpose for these icons is to work on the app and not in automatic tools - which they do fine. I currently don't have enough time to go through hundreds of icons one by one cleaning them up, but if you'd like to do that, feel free to clean them and submit a PR and I will merge it. :-)
