### ISSUE TITLE
Feature Request: Remember choice of whether ST wants vote history to be visible to players

### ISSUE THREAD

**Issue by eddgabriel** [bra1n/townsquare#182]
Relatively simple: massively approve of the new toggle allowing ST to hide the nomination/vote history from players, but can we have it be stored for an ST? At the moment the ST has to remember to untick that box every time they start a new session.

**Comment by bra1n** [comment]
Oh yeah, that was already planned but we tried to keep the initial release as simple as possible. Thanks for the reminder! :)

**Comment by nicfreeman1209** [comment]
it was done but think it just got forgotten! https://github.com/bra1n/townsquare/pull/169

**Comment by bra1n** [comment]
The vote history is not going to be visible to the players in the official app, so this is no longer going to be an issue.
