### ISSUE TITLE
Feature Request: Show Jinxes in Choose & Assign Modal

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#183]
**Is your feature request related to a problem? Please describe.**
Certain characters have interactions (jinxes), which might affect setup (or potentially be banned from both being in play).
It would be nice if ST could see these interactions before assigning roles.

**Describe the solution you'd like**
Similar to the current way a warning for setup changes is shown, a warning for jinxes could be shown, either on one of the characters, or possibly both characters. Jinxes should be shown iff both characters are selected.

**Additional context**
Townsquare tool already shows Jinxes in the Reference

**Comment by bra1n** [comment]
Sounds like a reasonable idea. Let's see when someone has time for it. :-)

**Comment by bra1n** [comment]
Added to the wishlist of the official app, but it won't be a part of this one.
