### ISSUE TITLE
Feature Request: Support for non-execution / exile vote, e.g. Cult Leader

### ISSUE THREAD

**Issue by magroader** [bra1n/townsquare#184]
**Is your feature request related to a problem? Please describe.**
We've been playing with Cult Leader. Cult Leader lets everyone - alive, dead, or dead and spent their vote already - to vote. This doesn't work great with the existing execution mechanic. Also, there is no "Nominator" for this.

**Describe the solution you'd like**
Some way to cause a vote that is neither an execution nor an exile. Perhaps could be cult-leader-specific, or could be some generic thing.

Perhaps the menu, next to Nominate, could be "Call for a vote"?

This could also be only applicable in games with a Cult Leader, or in games where your JSON has some setting to enable it.

**Comment by bra1n** [comment]
Yeah this is something I've wanted to add for a while, unfortunately I haven't found the time for it yet.

**Comment by bra1n** [comment]
This will be a feature in the upcoming official app, where certain roles get individual tools that allow them to be used better, like a Cult Leader on the script enables the ST to run a "Cult vote".
