### ISSUE TITLE
Bug: Incorrect wording on Pukka otherNight text

### ISSUE THREAD

**Issue by TopTierKitchenTools** [bra1n/townsquare#185]
**Describe the bug**
Incorrect text for [line 661 on roles.json](https://github.com/bra1n/townsquare/blob/develop/src/roles.json#L661). With the new almanac, the text should be replaced from "The poisoned player dies. The Pukka points to a player. That player is poisoned." 
to "The Pukka points to a player. That player is poisoned. The previously poisoned player then dies."

**To Reproduce**
1. Go to Night Roles or hovering over Night Order Number in Tool to display OtherNight text from roles.json.

**Expected behavior**
"The Pukka points to a player. That player is poisoned. The previously poisoned player then dies." should appear.

**Additional context**
BMR Almanac : https://drive.google.com/file/d/1vmvUPUwUyIvzwG-3cMg9FXJNZUBY1TPI/view

Screenshot of Almanac Text
![pukka-text](https://user-images.githubusercontent.com/86017002/122268266-b6a7e100-ce90-11eb-9672-d3677f70b08f.PNG)

**Comment by bra1n** [comment]
@eddgabriel ☝️
