### ISSUE TITLE
Bug: Mephit / Mezepheles not showing up in tool.

### ISSUE THREAD

**Issue by TopTierKitchenTools** [bra1n/townsquare#188]
**Describe the bug**
Mephit being renamed to Mezepheles has broken the ability to add that role into the townsquare, as well as view Roles or Night Order.

**To Reproduce**
1. Add {"id":"mezepheles"} to a custom json
2. Host a Clocktower session, select Edition, select Custom Script / Edition and upload custom JSON
3. Add players and try to set one as a Mezepheles, or view Roles or Night Order.

**Expected behavior**
View Roles, Night Order and select the Role should show the Mezepheles from the roles.json.

**Additional context**
It appears that there is some legacy text / images for the mephit; i.e. -> /assets/icons/mephit.png.

**Comment by bra1n** [comment]
Hey, it's the first time I hear about this change and the official script tool and almanac entry on the unofficial discord also call it Mephit. Do you have an official source for this?

**Comment by bra1n** [comment]
Alright, I just found out that @eddgabriel's last PR accidentally included this change which was not supposed to go live yet, so I reverted it back to "Mephit" until the official script tool has also been adjusted.
