### ISSUE TITLE
Feature Request: Drag & Drop custom scripts

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#191]
**Is your feature request related to a problem? Please describe.**
While custom scripts can be loaded quite easily, often multiple clicks are required to actually load a script (in addition to having to find the file on your computer through the choose a file window)

**Describe the solution you'd like**
Dragging & dropping a JSON file onto the townsquare window should immediately load the script (if not in game or ST).

**Describe alternatives you've considered**
Instead of the whole window being a proper space to drag the file, it might be a valid alternative to simply make the script choosing modal accept dragged files.

**Comment by bra1n** [comment]
Good idea!

**Comment by bra1n** [comment]
And implemented in the official app.
