### ISSUE TITLE
Bug: Issues with night order, unknown cause

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#193]
**Describe the bug**
Under certain conditions, night orders will go berserk and repeat.
This issue was originally noticed while experimenting with negative night orders.

**To Reproduce**
1. ???. ([Working example](https://pastebin.com/raw/Ypfw8yXR))
2. Make a 15 player game
3. In Choose & Assign modal, select all non-Townsfolk characters, and assign them randomly
4. Notice, that Outsiders have night order numbers (with repeats), even though some of them should not act at night. (This step might require multiple repeats)

**Expected behavior**
Night orders should not repeat.

**Screenshots**
![image](https://user-images.githubusercontent.com/46909274/123554006-c4aa0b80-d786-11eb-9a80-8275976dfb6f.png)
![image](https://user-images.githubusercontent.com/46909274/123554001-c1168480-d786-11eb-9824-d635966db09b.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Browser: Mozilla Firefox for Linux Mint (mint - 1.0)
 - Version: 89.0.1 (64-bit)

**Comment by bra1n** [comment]
I'll take a look, but the most likely outcome is probably going to be that I'll just update the README with "don't use negative night order numbers". 😉

**Comment by JulGvoz** [comment]
I believe I observed the issue even after I didn't use negative numbers (though I might've failed to properly refresh page, make sure that no cached versions of characters remained)
In any case, the fact that negative numbers cause an issue here is bizarre, though it's too niche to properly look into

**Comment by bra1n** [comment]
Negative night order positions are now converted to positive night order positions.
