### ISSUE TITLE
Bug: Other Travelers modal shows up when choosing Demon bluffs

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#194]
**Describe the bug**
In certain situations, "Choose a new character for bluffing" modal lists Other Travelers

**To Reproduce**
1. Assign a Traveler character to any player (must be from Other Travelers modal)
2. Make sure NOT to switch back, but specifically close the modal by assigning the Traveler
2. Click on empty Demon bluffs token
3. Observe that Other Travelers show up (instead of not-in-play characters)

**Expected behavior**
Not-in-play characters should show up, no matter what the host did before in the townsquare. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46909274/123610058-e8159a80-d808-11eb-9523-42aea4cbb60d.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Browser: Mozilla Firefox for Linux Mint (mint - 1.0)
 - Version: 89.0.1 (64-bit)

**Comment by bra1n** [comment]
Nice catch, thanks!

**Comment by bra1n** [comment]
Thanks, fixed!
