### ISSUE TITLE
Add an obvious UI element (such as a banner) prompting a user to claim a seat

### ISSUE THREAD

**Issue by mvanderkolff** [bra1n/townsquare#201]
One of the common newbie issues with the interface is the need to claim a seat.

One potential solution would be to add a banner or something, with a context menu showing unclaimed characters.

**Comment by bra1n** [comment]
Thanks for the issue report! I agree, that claiming your seat is not really obvious to first-time players, but it also has to be balanced with not cluttering the interface for spectators that don't have to claim a seat. I'll think about how to improve it...

**Comment by bra1n** [comment]
This is going to be remedied in the official app and since it is not a bug, it won't be fixed here. :-)
