### ISSUE TITLE
Feature Request: Add players by comma separated list

### ISSUE THREAD

**Issue by TwistedIsles** [bra1n/townsquare#212]
**Is your feature request related to a problem? Please describe.**
While playing on the unofficial BOTC discord, I have noticed that Storytellers often have to add a large number of user to their grim. The Storyteller should be able to add a list of players without having to repeatedly press "add player"

**Describe the solution you'd like**
* Add a new button to the player menu ("Add (List)")
* The ST is warned that this process will clear the current grim
* The ST specifies a list of players, separated by commas
* Each of the players are added to the grim

e.g. "Tom, Richard, Harry" becomes three players with the labels "Tom", "Richard" and "Harry"

**Describe alternatives you've considered**
* Additional logic could be added to combine the existing players with the new list, but I dont think that is necessary for the initial implementation
* Successive "Add Player" dialogues could be used instead, accepting player names until the ST clicks cancel, or the grim is full.

**Additional context**
* a command could then be added to https://github.com/bra1n/grimoire to generate the comma separated list for the ST

**Comment by bra1n** [comment]
In the official app, players can provide their own names for their seats, so the ST will only have to add X empty seats with X clicks, speeding up the process a lot.
