### ISSUE TITLE
Feature Request: Changeable Travelers (Travellers)

### ISSUE THREAD

**Issue by pinual** [bra1n/townsquare#223]
**Is your feature request related to a problem? Please describe.**
There are a few interactions for Travelers that cause the grimoire to no longer show them as a Traveler.  The first being an Apprentice.  The instruction for running in the rules and Townsquare app first night instruction tells us we should replace their token with what they become.  [Side Note: This only shows on First Night reminder but it should be on Other Nights as well, similar to how you have the Juggler reminder for Other Nights, if it it is there first night.]  Changing their token is very helpful with remembering to wake them if they have an at night ability, especially since in my case, I've become dependent on using the numbers next to tokens as a reminder rather than constantly consulting the night order list.  The problem with doing this is that the player no longer registers as a Traveler for the sake of player count numbers in the center of the screen and for votes to Exile.

The other interaction where this comes in to player is the Pit-Hag or Barber causing the Traveler to change into something else.  I cannot find official rules about this however the [wiki for a Pit-Hag](https://bloodontheclocktower.com/wiki/Pit_Hag) says; "You can transform Travellers... maybe. The rules are still being worked out on this one. Watch this space." Some say it should only be done with advanced players but I have a fairly advanced group.  In addition to the concern above, there is also the potential that if I change the Traveler to something else, this information is immediately seen by everyone using the Townsquare app because Travelers are shown to everyone in the grimoire.  Typically only the Storyteller would see the grimoire and changing that would not provide evidence to the players that the change occurred.  

**Describe the solution you'd like**
I would like a solution that allows me to change the Traveler's character without changing the fact that they are a Traveler.  In the Apprentice case, it would require that the "Is Apprentice" token make the player register as a Traveler but I recognize this is difficult since this status is usually only taken from the character json.  To accommodate the Pit-Hag/Barber, the rules are not clear as to whether that player would still be a Traveler but we do need a way to not show everyone that the change occurred.  I think this would mean needing the Travelers not to be enforced in the grimoire but broadcast instead similar to how Send Characters works, where people can manipulate it in their grimoire and the Storyteller can change it without others seeing it.

**Describe alternatives you've considered**
Alternative solution is to disregard the rule guidance and have reminder tokens say something like "Empath Ability" meaning that the Apprentice who has the Empath Ability would have this token and that token is given a reminder number for the night order.

**Additional context**
N/A

**Comment by bra1n** [comment]
The thing with the Apprentice is, that in a physical grimoire there is no way to remember what ability they gained short of replacing their token with the character that has their new ability. This is explained in the almanac as well. The digital app does not have this problem and the player in fact stays a Traveller and an Apprentice. In the digital app, I would simply add a custom reminder with the name of the character whose ability they received.

Concerning the Pit Hag and Barber, I think the latest ruling there has been that those ability can't target a Traveller, so this would also no longer be an issue. I'll close this ticket for now, but that doesn't mean there isn't going to be a better solution for handling the Apprentice specifically in the app. 😃
