### ISSUE TITLE
Feature Request: Ability to display Grimoire to Players

### ISSUE THREAD

**Issue by davotronic5000** [bra1n/townsquare#23]
It would be a nice feature to be able to display the Grimoire to all players at the end of the game for the run-through,  As an extension of this being able to allow a spy to view the grimoire at the right time.

**Comment by bra1n** [comment]
I could add a "show Grimoire to players" toggle, but that would be kinda risky to accidental clicks. Showing the grimoire only to the Spy is not possible unfortunately, as that involved sending messages to the websocket that every single player is connected to and they would be able - with some technical prowess - to read these messages.

**Comment by decker9000** [comment]
Wouldn’t taking a screenshot with the button by the menu and pasting into chat so everyone (or only the spy’s chat) can see have a similar effect?

**Comment by bra1n** [comment]
Basically, yes. This is what the screenshot button is there for, or taking a screenshot yourself. Currently I'd say it would be too much work to add a feature to sync the *full* gamestate.

**Comment by davotronic5000** [comment]
that is fair enough, it is definitely only a QOL thing,  we are currently running games fine with screenshots of the tool.

**Comment by cyrusDAVO** [comment]
RE: the toggle option, to prevent accidental clicks you could add a 'confirmation modal' of sorts -- 'Are you suuuure you want to do that?'

**Comment by bra1n** [comment]
Of course, but this still leaves the issue that you can't secretly send data through a live session to only one other player. If you "show the Grimoire" to someone, everyone would be able to see it.

**Comment by cyrusDAVO** [comment]
Yep, I hear that -- would have to be for the whole town

**Comment by bra1n** [comment]
I don't think there is a technically feasible solution that would not clash with players using the Grimoire to keep notes, so I'm closing this for now. If you really need to share the actual Grimoire (versus, say, a screenshot of it), you can now simply share the game state JSON with that player and they can then load the Grimoire in an incognito browser tab, for example.
