### ISSUE TITLE
Bug: NODE_ENV=development node index.js error

### ISSUE THREAD

**Issue by stonyme** [bra1n/townsquare#237]
**Describe the bug**
when I  enter 
npm install
cd server/
NODE_ENV=development node index.js
the console tell me error,
![image](https://user-images.githubusercontent.com/21095021/147633733-4c9c2194-6c45-4a21-91f1-8b3941688454.png)
So I add key.pem and cert.pem file,run it again,The console is not responding。I just run it locally,how to run the backend?

**Desktop (please complete the following information):**
 - OS: MAC 
 - Browser:chrome
 - Version  node version:v14.17.0

**Comment by bra1n** [comment]
Hey @stonyme,
as the README for the server describes, you need to create your own (localhost) certificate files. For example, you could follow this [Stackoverflow answer](https://stackoverflow.com/a/12907165/1552315).
