### ISSUE TITLE
Bug: Character selection text layers improperly resize after mouseaway (Chrome only)

### ISSUE THREAD

**Issue by bigheadzach** [bra1n/townsquare#238]
**Describe the bug**
When on the "Choose & Assign" screen, mousing away from a token causes the gray background layer with the text to appear smaller than normal and top-left aligned.

**To Reproduce**
1. Add enough players so that you can access the Choose & Assign modal
2. Mouse over a token so that it enlarges and highlights.
3. Mouse away.

**Expected behavior**
The token layers un-enlarge themselves and return to correct normal size in their unfocused state.

**Screenshots**
![image](https://user-images.githubusercontent.com/1135856/148574825-8f523458-c821-43fb-a88e-088c71529e6a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterrey
 - Browser: Chrome 96.0.4664.110

**Additional context**
When inspecting the HTML to understand the nature of the problem, the properties of the layer looked correct, just incorrectly rendered. If I manipulated any of the properties belonging to the SVG layer involved, the layer would re-render and correct itself - so it appears to only happen as a consequence of the size/zoom change.

**Comment by bra1n** [comment]
Thanks for the bug report, @bigheadzach! This is actually a bug in Chrome, which as been fixed with version 97: https://bugs.chromium.org/p/chromium/issues/detail?id=1270713&q=svg&can=2
I'd suggest updating your browser to fix it on your end.
