### ISSUE TITLE
Damsel First Night

### ISSUE THREAD

**Issue by pinual** [bra1n/townsquare#239]
The app's timing of the Damsel for both first and other nights is directly after the Huntsman.  I believe this is to be a reminder if they were selected by the Huntsman.  The first night reminder saying to wake minions should not actually occur at this time according to @eddgabriel 's post on the Discord server.  It should happen during Minion info.  I believe the text for the Damsel on the first night reminder should match the other night reminder.

"firstNight": 28,
"firstNightReminder": "Wake all the Minions, show them the 'This character selected you' card and the Damsel token.",
"otherNight": 49,
"otherNightReminder": "If selected by the Huntsman, wake the Damsel, show 'You are' card and a not-in-play Townsfolk token.",

**Comment by bra1n** [comment]
Let's see what @eddgabriel thinks about this. 😄

**Comment by bra1n** [comment]
Sorry for the delay, I've talked to Edd and this is not going to change for now.
