### ISSUE TITLE
Bug: Image inconsistencies

### ISSUE THREAD

**Issue by LectronPusher** [bra1n/townsquare#246]
All images added after May 2021 (after the automatic image cleanup here https://github.com/bra1n/townsquare/pull/178) are of a different size and position (centered instead of having a transparent offset from the bottom) than the cleaned ones. Wondering if @JulGvoz could run their script again to make all images have the same positioning and location.

This affects my new [custom script generator](https://github.com/LectronPusher/botc-custom-script-generator) because the newer images don't trim the same as the older images, and it makes them fail to render properly in Latex.

Also if the script is run again, can the images be centered this time instead of having a transparent offset from the bottom? This would help with adding custom characters whose images will probably also be centered and I won't have to add options for centered/not.

**Comment by bra1n** [comment]
Since @JulGvoz lost their script and I'm focusing on the official app now, I'm afraid you'll have to post-process the new icons yourself, if you need them. Sorry!
