### ISSUE TITLE
Feature Request: we need chinese ,thx.

### ISSUE THREAD

**Issue by ltdstudio** [bra1n/townsquare#250]
Hi , anthor , This is good project, Can you add chinese？ I can do something like this project : https://github.com/ltdstudio/terraforming-mars/tree/main/src/locales

**Comment by bra1n** [comment]
Hi @ltdstudio, there are plans to add translations for the official app, but it will still take a while. Meanwhile, this open source version is no longer maintained and will be superseded by the official app soon.
