### ISSUE TITLE
Feature Request: Changing the name of the "Grimoire" tab to "Town Square" for the players

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#26]
Currently, the first tab is called Grimoire but for the players that doesn't really reflect what that tab does. I think it should be renamed to "Town Square" and the first button should read "Show Notes" instead of just "Show". 

The Night order button could also MAYBE be hidden for the players? they don't NEED that info (plus if they have a vague sense of who the Storyteller might be talking to it's actually a problem) and it's always good to remove extra stuff from menus.

**Comment by bra1n** [comment]
Well, but it *is* the Grimoire... only the one for the player? I mean, in the end, the tool is supposed to be primarily used by Storytellers and (optionally) by players for voting, too. I'll think about renaming some parts of it for live session players, but in the end it might not be worth the effort.

I do disagree with the night order part though. Especially when you've played a few games before, knowing the night order sometimes is important for decision making, so I'll definitely leave that button in.

**Comment by unrealed** [comment]
To me, the Grimoire is what the Storyteller has that shows people's true roles, so having that as a button for new players is confusing. I assume that it's called the "Grimoire" by association to the "Storyteller", so it should only be available to him. This isn't the most urgent request tho.

Fair for the night order.

**Comment by bra1n** [comment]
Well, it's called the "Grimoire" because that's what the official name is for the place where all the player tokens are. ;-)

**Comment by bra1n** [comment]
Closing this for now, as it seems like this is not an issue shared by many other users.
