### ISSUE TITLE
Feature Request: Whether it's a way to customize a new role?

### ISSUE THREAD

**Issue by GrainLee** [bra1n/townsquare#260]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bra1n** [comment]
Hi @GrainLee ,
[this](https://github.com/bra1n/townsquare#custom-character-support) should cover what you're looking for. There are also other pages that let you generate full scripts of homebrew characters, like https://www.bloodstar.xyz/
