### ISSUE TITLE
Feature Request: Adjustable voting clock speed

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#27]
It would be really great to be able to set the speed of the clock. Ideally, there would be a number that shows you how many seconds it will take to reach each successive players (and the total that would make when multiplied by the number of players)

**Comment by bra1n** [comment]
That's already on the to-do list. 😄 I plan to add a 1s and 2s delay (versus the 3s we have now). What would you gain from showing the total voting duration? I'd rather keep it as simple as possible and not clutter the space with unnecessary data.

**Comment by unrealed** [comment]
Well I was hoping we could just choose whatever number we want. For higher player counts 1-3s is good enough, but at lower player counts 3s seems very fast to me. And it's better to just let the ST decide what is best for the situation. I think it's sometimes fun to make it very quick (and useful if the game's been dragging on) and sometimes there are rounds with really really tough game-deciding decisions that require more time for players to choose.

The way I envision it is just a text box with + - buttons around it that add/remove 1 second, text just above this that reads "Seconds before clock hand reaches the next player", and smaller text underneath it that reads "(Total: x seconds)". I don't imagine this would be very cluttered, especially if you hide it all behind a button by default (though I'd prefer it not to be).

**Comment by bra1n** [comment]
Done!
