### ISSUE TITLE
Bug: Philosopher night reminder text error

### ISSUE THREAD

**Issue by StroginA** [bra1n/townsquare#271]
**Describe the bug**
Philosopher's night reminder text (both First Night and Other Night) refers to a "Not a Philosopher" token.

**To Reproduce**
1. Add a Philosopher to the game
2. Hover over the night reminders

**Expected behavior**
The actual token has the text "Is the Philosopher", and should logically have it. The night reminder is expected to cite the corrent text on the token.

**Comment by bra1n** [comment]
Thanks, I updated the reminder text: https://github.com/bra1n/townsquare/commit/ea5b3c523fde4a3ae05927b8e779a99779bd3d94
