### ISSUE TITLE
Feature Request: Minimizing Demon bluffs

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#29]
It would be great if we could minimize the Demon bluffs when viewing the Grimoire. When the screen is tight horizontally (like if it's displayed over half your screen) the Demon bluff window tends to overlap the roles. 

Also, it's not really a useful feature for the players to have, so it should be minimized for them from the start

**Comment by bra1n** [comment]
Actually, I found the extra space to remember some roles useful, as a player, as well. But I agree that it would make sense to allow someone to minimize the box.

**Comment by unrealed** [comment]
I'm not against having it for players, but minimized by default would still be nice

**Comment by bra1n** [comment]
Done!
