### ISSUE TITLE
Demon bluffs not saved on reload

### ISSUE THREAD

**Issue by nwarford** [bra1n/townsquare#3]
Noticed this last night - the rest of the state was saved except for the Demon's three bluffs.

**Comment by bra1n** [comment]
Thanks for the ticket, I actually already fixed this in the next build. :-) Give me a couple of days and it should be ready for deployment.

**Comment by nwarford** [comment]
Sure thing! (I’m also Noel on the community Discord)

Cheers,

Noel

**Comment by bra1n** [comment]
Should be fixed now!
