### ISSUE TITLE
Feature Request: Night Order

### ISSUE THREAD

**Issue by JamesParrish** [bra1n/townsquare#30]
It is helpful for players to know the night order, for example to help with bluffs or to help catch people in bluffs. It would be very useful to have an option to bring up the night order, similar to bringing up the Reference Sheet by pressing R.

A couple of ideas I had for this are:

- Add tabs to the existing Reference Sheet for night 1 order and subsequent nights order.
- Add a new modal with two tabs, one for each order
- Add two new modals, one for each order

Cheers,

J

**Comment by unrealed** [comment]
For both players and the Storyteller, you can see the night order by going to the Grimoire tab then showing the grimoire with "night order" box checked

**Comment by JamesParrish** [comment]
If you're talking about what I think you're talking about (ie showing the numbers on the player's circles) then that has a few drawbacks - it only shows if you have the role assigned to someone and it hides the numbers for dead people, Having a list that you can pull up would let you check things without assigning roles.

An example use case is wanting to check whether a role acts before or after the demon. As a good player, in most cases I won't have a demon assigned to a character so I can't compare their priorities without changing someone else's role to demon. It would be useful to be able to bring up the night order to compare the priority of two specific roles without having to assign both of them to alive players.

**Comment by bra1n** [comment]
This is a *great* idea! I've been missing something like that myself (as a player), so I'll definitely add it. Most likely to the reference modal as a tab, as you suggested.

**Comment by bra1n** [comment]
Done!
