### ISSUE TITLE
Bug: New Characters

### ISSUE THREAD

**Issue by Kingofawesome14** [bra1n/townsquare#306]
**Describe the bug**
The tool allows you to create scripts with the new characters in it, and to choose those scripts. But when you assign players, those new players aren't there to assign so the script is incomplete and you can't play as the new characters.
**To Reproduce**
1. Choose a script with a new character, such as the Harpy
2. Go to the choose and assign tab
3. The new characters are not able to be played and will not appear

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bra1n** [comment]
Hey @Kingofawesome14,
as outlined in the README (https://github.com/bra1n/townsquare#blood-on-the-clocktower-grimoire--town-square), this project will no longer receive content updates, for the time being. If you want to play with the newest characters, I'd suggest taking a look at the official app (https://www.patreon.com/botconline)
