### ISSUE TITLE
Feature Request: Make Demon Bluff window display on top of the roles

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#32]
The Demon Bluff window can be overlaid by the roles in vertically shaped browser windows. 

I think you should make IT overlay the roles instead. That way it's fine if it covers up the roles since we can close that window again anyway

Example of the problem (I'm trying to close the Demon Bluff window):
![image](https://user-images.githubusercontent.com/3929975/85045520-5acc4e80-b18f-11ea-9b72-ec201797b297.png)

**Comment by bra1n** [comment]
Agreed, makes sense.
