### ISSUE TITLE
Feature Request: add storyteller prompts for Demon and Minion Info to town square

### ISSUE THREAD

**Issue by Lucretiel** [bra1n/townsquare#328]
**Is your feature request related to a problem? Please describe.**

I often forget to do the initial minion and demon steps; it would be nice if the blue night 1 sequence numbers included a step for this 

**Describe the solution you'd like**
Add blue numbers 1 and 2 corresponding to demon info and minion info, and then start the first character's power (e.g., the Chef) at 3.

**Describe alternatives you've considered**
Alternatively, use a blue asterisk or something similar, for clarity with powers like the Chambermaid.

**Comment by bra1n** [comment]
Hi, this project is no longer being actively maintained. You can use the [official app](https://botc.app) or one of the other free clones available.
