### ISSUE TITLE
Bug: Night sheet button in reference sheet not doing anything

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#33]
For me the little night sheet button in the top left of the reference sheet isn't doing anything

(I just double clicked it and it selected the text to the right)
![image](https://user-images.githubusercontent.com/3929975/85046177-56ecfc00-b190-11ea-9cc9-c9c0360ff857.png)

**Comment by JamesParrish** [comment]
Same issue for me, replicated on Chrome, Firefox and Edge. I've disabled cache and hard reloaded, but still nothing. There are no errors or warnings in the console. The page tells me it's running v1.1.0

**Comment by bra1n** [comment]
Oops, my bad. Fixed!

**Comment by JamesParrish** [comment]
Works fine for me now. Looks good, cheers!
