### ISSUE TITLE
Show Story Teller What the Drunk thinks they are

### ISSUE THREAD

**Issue by Ellamental2** [bra1n/townsquare#330]
Currently:

Storyteller view:
![image](https://github.com/user-attachments/assets/2dd0cf44-8a30-4dce-8853-10f54684d31d)

Player View:
![image](https://github.com/user-attachments/assets/bb89656b-e4f2-4bc7-99b0-f28f3e9eb54f)

Suggested StoryTellerView:

![image](https://github.com/user-attachments/assets/5d4c6e94-ce2c-4b68-9c41-28a0040867af)

with the blue/red numbers adjusting accordingly

**Comment by bra1n** [comment]
Actually, the Storyteller is also supposed to use the Investigator token for the drunk player and in addition to that, add an "Is the Drunk" reminder token.
That said, this project has been superseded by the [official app](https://botc.app) and is no longer being actively maintained.
