### ISSUE TITLE
Bug: You can "Prevent this page from opening additional dialogues" which breaks adding/randomising players

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#34]
**Describe the bug**
There appear to be 2 kinds of "Add Player" diaglogue boxes.

If you select the box to "Prevent this page from opening additional dialogues" then you can no longer add any other players (because the dialogue box is prevented).

**To Reproduce**
1. Refresh the page
2. Add a player (this produces the first pictured dialogue box). Cancel.
3. Add a player (this produces the second pictured dialogue box). Check the box to prevent additional dialogue boxes.
4. Add a player (either through the menu or using the shortcut).Nothing happens.

**Expected behavior**
You should either:
1. Not be allowed to "Prevent this page from opening additional dialogue boxes"
2. Allow players to be added even if dialogue boxes are prevented.

**Screenshots**
![image](https://user-images.githubusercontent.com/3476614/85058605-404ba280-b19a-11ea-9e00-c6c7ddbb1e50.png) and 
![image](https://user-images.githubusercontent.com/3476614/85058622-480b4700-b19a-11ea-9be4-ee1f97ad1e17.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 77.0.1

**Comment by bra1n** [comment]
This is a browser thing, there's nothing I can do about it on my end. If a user decides to block popups, then that will cripple the page the same way as if they decided to use an adblocker or disable javascript. As a workaround, the popups will show up again when you reload the website.
That said, I might add some custom in-page dialogues in the future, which won't require any browser-side popups anymore.

**Comment by bra1n** [comment]
For reference: https://stackoverflow.com/a/11729866/1552315
