### ISSUE TITLE
Feature Request: Hotkey for night order

### ISSUE THREAD

**Issue by JamesParrish** [bra1n/townsquare#36]
As it stands there is no hotkey to show the night order. Please can you add a hotkey to show the night order screen?

This could either be a new hotkey (eg n for night) or changing r to cycle between role sheet, night order and hidden. I suspect a new hotkey would probably be best practice to avoid confusing people who already use r to toggle the role sheet on and off.

**Comment by JamesParrish** [comment]
Additionally, I've just noticed that bringing up the role list (either by pressing r or selecting the menu option) remembers the previous state of the screen (ie whether it shows the role list or the night order). I don't know whether this is intended or not?

**Comment by bra1n** [comment]
Hotkeys should only be for the main options of the menu, not for sub-screens inside a popup... 🤔 It would also be a bit harder to implement with how hotkeys are implemented right now. What I *can* do is add another menu entry for the night sheet and have that open the night reference right away and bind it to a hotkey.

> Additionally, I've just noticed that bringing up the role list (either by pressing r or selecting the menu option) remembers the previous state of the screen (ie whether it shows the role list or the night order). I don't know whether this is intended or not?

That's intended, but if I add the feature described above, I'll probably change it. 😃

**Comment by bra1n** [comment]
Done, it's a separate modal now and bound to "N".
