### ISSUE TITLE
Feature Request: Add a Drunk reminder token when the Drunk isn't in play

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#37]
**Is your feature request related to a problem? Please describe.**
In Trouble Brewing, currently the only time the Drunk reminder token appears is when the Drunk is in play. The Drunk reminder token is for reminding the Storyteller which Townsfolk role is drunk. At the moment, the only way is to add a custom token that says Drunk to reminder you as the storyteller.

**Describe the solution you'd like**
The Drunk reminder token to be available when the Drunk isn't in play.

**Describe alternatives you've considered**
Role reminder tokens for the Drunk character token, but that's a lot more tokens and not how it works in the real Grimoire. In that, the players are given the Townsfolk role token and then there Storyteller puts the Drunk reminder token. There is no "Drunk" character token.

**Additional context**
![unknown](https://user-images.githubusercontent.com/3476614/85234307-62485d80-b404-11ea-81b4-2356418ce9dc.png)

**Comment by bra1n** [comment]
Hi Geoff,
thanks for the ticket! The way to use the Drunk right now is like this: assign a player the Drunk role, add the Drunk reminder token to them and *then* assign them the role they believe to be. Currently, there are no "always available" reminder tokens, but I created  a todo task a while ago to look into this problem a bit more.

**Comment by AdmiralGT** [comment]
Ah OK. So need to, select all the roles, then choose the Drunk character, make them the Drunk character, set the Drunk reminder token, then set back to the supposed character token.

**Comment by bra1n** [comment]
> Ah OK. So need to, select all the roles, then choose the Drunk character, make them the Drunk character, set the Drunk reminder token, then set back to the supposed character token.

Exactly!

**Comment by bra1n** [comment]
Alright, now that there's Lil' Monsta, I feel like it's a good time to add a feature for reminder tokens that are shown even when the role is not assigned to a player...

**Comment by bra1n** [comment]
And it's done. Drunk (and Lil' Monsta) now have "global" reminders that will be selectable even when the role is not assigned to any player.
