### ISSUE TITLE
Bug: Rooms starting with an upper case letter are not displayed

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#39]
**Describe the bug**
If you create a room with a word, and start with an upper case letter, it is not displayed.

**To Reproduce**
1. Create a room named `Ellen`
2. View the room name, it is listed as `llen`
3. The room however is actually named `Ellen`

**Expected behavior**
The room should be displayed as `Ellen`

**Screenshots**
![image](https://user-images.githubusercontent.com/3476614/85902165-46292f80-b7fb-11ea-9c10-440b9a36c814.png)

**Desktop (please complete the following information):**
Multiple people have said this occurs for them so pretty sure OS/Browser/Version is irrelevant.

**Comment by AdmiralGT** [comment]
I've done a bit more digging into this.

- If you host a session with an ID in all uppercase, no session is created
- If you host a session with an ID of a mix of uppercase and lowercase letter, you can join the session using either the full ID (of upper and lowercase letters) or the lowercase ID (just the lowercase). So ID `Geoff` can be joined using `Geoff` or `eoff` and ID `geOff` can be joined using `geOff` or `geff`

**Comment by bra1n** [comment]
Yeah, currently any non-lowercase, non-numeric character is removed from the channel name when you enter it. I should probably fix this to allow uppercase letters as well. :-)

**Comment by bra1n** [comment]
Fixed, now you can also enter uppercase letters and it doesn't matter if a letter is upper or lower case.
