### ISSUE TITLE
Feature Request: rename master

### ISSUE THREAD

**Issue by Julzerator** [bra1n/townsquare#40]
**Is your feature request related to a problem? Please describe.**
In society at large we are facing a reckoning about how we use racially termed language. I love the BotC community and how we are so open to issues and lie to each other so much, but are generally a great group. I work in tech and there has been a big push to move from master/slave, whitelist/blacklist, and other 'legacy' terms and I think changing the name of master to 'main' would be a good step in the right direction.

**Describe the solution you'd like**
Update `master` to `main` or `trunk`

**Describe alternatives you've considered**
n/a

**Additional context**
https://www.lifehacker.com.au/2020/06/ditch-these-racist-terms-from-your-tech-vocabulary/

**Comment by bra1n** [comment]
Done, the main branch is now "main". :+1:
