### ISSUE TITLE
Feature Request: Open the "Night Order" screen using [R] if previously viewed using the toggle

### ISSUE THREAD

**Issue by LukeC82** [bra1n/townsquare#45]
**Is your feature request related to a problem? Please describe.**
Observation: After pressing the hotkey [R] you must always mouse-click the upper-left toggle to view the Night Order sheet each time.

Current behavior:
When clicking on the Reference Sheet menu item, or using the hot-key [R], the "Character Reference" is displayed first.

If you toggle the screen to show the "Night Order", this is not remembered if the window is close & later re-opened.

**Describe the solution you'd like**
I suggest that if a user has toggled the "Character Reference" to "Night Order" that is remembered for that session.

Using [R] would therefore open the Night Order if that what they used last time, or Character Reference of that's the case.

**Describe alternatives you've considered**
I am aware the Night Order is presented on the Character Tokens (numbers) which is great, but I personally find reading the sequenced Night Sheet easier - by allowing this Night Order to be quickly viewed with [R], I think the experience is improved.

**Additional context**
Perhaps a separate request, but can the Night Order sheet be filtered to only show Characters in play? This would be an excellent addition!

**Comment by bra1n** [comment]
Hi Luke,
what you described was how the night order screen worked previously. Not it is split into its own menu point and can be accessed by pressing "N". I think that this is the better solution, so I won't revert the changes. Filtering them to only the characters in play would be redundant with what is shown on the tokens, plus as a player you usually want to know the whole night order anyway.
