### ISSUE TITLE
Feature Request: Keep Night order tokens for Dead players

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#47]
**Is your feature request related to a problem? Please describe.**
Situation occured in the [Live Stream
](https://www.twitch.tv/thepandemoniuminstitute) where the Moonchild was killed during the day, selected someone to die, but they were protected by the Innkeeper. This is the correct night order (Innkeeper comes before Moonchild death) but it's difficult as the ST to see this because the Moonchild night order is removed when they die. This also happens for minions killed by the Vigormortis, they still have their night order position removed, even if you give them the Vigo reminder token that their still active, they don't get a night order.

**Describe the solution you'd like**
Night order remains intact for dead players (perhaps grey them out to indicate they are dead)

**Describe alternatives you've considered**
This perhaps could only be applied to particular night roles where they have an impact while dead e.g. Moonchild and when minions have active ability tokens but I feel it's easier to just have all roles when dead have their night order.

**Additional context**
![image](https://user-images.githubusercontent.com/3476614/87601244-9e619c00-c6ec-11ea-8dc8-3e792545b85c.png)
In this instance, the Cerenovus should still be 1 in the night order because they have an active ability but they don't have their night order displayed.

**Comment by AdmiralGT** [comment]
This also affects Zombuul even when they have their ability 
![image](https://user-images.githubusercontent.com/3476614/87607032-4dee3c80-c6f4-11ea-8779-8e01e93bd379.png)

**Comment by bra1n** [comment]
Hey Geoff, thanks a lot for the very well-written ticket! Initially, the night order was shown like you suggested, including dead players as well. I hid them when it became clear that most of the time (ie. in 95% of the games) it was not relevant. I can of course add it again, but I'd like to know how other people think about this first. Another option would be to add a toggle to the menu where you can turn this on or off. 🤔

**Comment by impatman** [comment]
I agree it should be a toggle. In Trouble Brewing games it wouldn't matter that much, but as new story tellers try out Sects & Violets or Bad Moon Rising it'd be good to not have to break muscle memory of finding each number in the circle.

**Comment by AdmiralGT** [comment]
I think a toggle would be a happy compromise.
