### ISSUE TITLE
Bug: If a player joins while a vote is occurring the hands go wonky

### ISSUE THREAD

**Issue by Binestar** [bra1n/townsquare#49]
**Describe the bug**
The hands of the vote clock goes crazy if someone joins the player session while a vote is occurring.  This is for everyone, not just the person joining.

**To Reproduce**
1. Storyteller starts a vote
2. A player joins the session while the vote is occurring.

**Expected behavior**
The vote should just continue without resetting and going weird.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.0.2 (64-bit)

**Comment by bra1n** [comment]
Thanks for the bug report, I fixed it. :-)
