### ISSUE TITLE
Zoom does not work on Firefox 76.0

### ISSUE THREAD

**Issue by daalta** [bra1n/townsquare#5]
![2020-05-08_12-20-52](https://user-images.githubusercontent.com/9169275/81396813-69522f80-9126-11ea-8c39-669aa42137ab.gif)

The player tokens cannot be zoomed when using Firefox.

Though zooming the entire web page with `CTRL` and `+` or `-` works.

**Comment by bra1n** [comment]
Hmm, I'm currently only using Chrome, so this is probably caused by some proprietory `zoom` CSS. I'll see if I can fix it.

**Comment by bra1n** [comment]
Fixed as part of the responsive update, will merge this soon-ish.

**Comment by bra1n** [comment]
Should be live now. :-)

**Comment by daalta** [comment]
Works beautifully.
