### ISSUE TITLE
Feature Request: Add Seat Indicators

### ISSUE THREAD

**Issue by ChrisRahn** [bra1n/townsquare#50]
**Is your feature request related to a problem? Please describe.**

We had a great time in a big 14-player game! However, communicating how the site works to that many people at once is tricky, and a few got confused how to claim their seat. There were also a few occurrences of people reconnecting and inadvertently vacating their seat (I think at least once they somehow refreshed as a host). It wasn't obvious to us when a seat was properly filled or not.

**Describe the solution you'd like**

An extra visual element to indicate a seat's status would help marshal a big game. Maybe empty seats could have a brightly-colored button on or nearby to claim them, instead of having to use the context menu? Or be grayed- or "X"ed-out somehow? If it's possible, each player's view could also have a thick outline around their current seat.

A clearer separation between the host and player version of the page could help, too. Maybe a different background?

**Describe alternatives you've considered**
A status bar or banner across the top could probably work, too ("You are playing as XXX", "You are hosting game xxxx").

**Comment by bra1n** [comment]
Hey Chris, thanks for the ticket!
There should be already a visual indicator for when a seat is occupied: 
![image](https://user-images.githubusercontent.com/325521/88576148-43616a80-d045-11ea-95cc-857a56226416.png)
And if the seat is occupied by *you*, it should turn blue:
![image](https://user-images.githubusercontent.com/325521/88576267-74419f80-d045-11ea-9f29-8c9f341f7e6b.png)
On top of that, when you switch to Grimoire view (press G), then the claimed player token gets a colored glow if it's your token:
![image](https://user-images.githubusercontent.com/325521/88576321-8b808d00-d045-11ea-81d3-97b101db871e.png)

I agree that this could be explained better, but I already plan to write a detailed README for players and storytellers in the near future. :-) Whether you're "playing" or "hosting" a session should also be shown in the top right corner of the page, where the "radio antenna" icon turns either blue (playing) or red (hosting), depending on which it is:
![image](https://user-images.githubusercontent.com/325521/88576415-b4a11d80-d045-11ea-90b5-a07f61ee7be2.png)

**Comment by bra1n** [comment]
Closing this for now, as it is already implemented.
