### ISSUE TITLE
Hover effect for role selection in the Grimoire

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#51]
It would be great to have an effect when you hover over a role circle in the Grimoire, to help you notice that there IS an invisible button that lets you select a player's role. There is one for the shroud's invisible button and that helps STs know that there is a button there and what it does, so one for role selection would be great.

I think a simple white, semi-transparent circle over the role token would suffice.

**Comment by bra1n** [comment]
Agreed, I'll add such an effect.

**Comment by bra1n** [comment]
Added, the token name will now show a hover effect.
