### ISSUE TITLE
First night evil info

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#53]
It would be nice to have first night reminders for the "Minion info", "Demon Info", & "Demon Bluffs" on the Night Order sheet and/or the on-token reminders. These would be the reminders for "who is your demon", "who are your minions", and "what you can bluff as the Demon", respectively. 

Having reminders on the token themselves would definitely be better, and I'd imagine them labeled as number 0, but you'd have to resolve the problem of roles that can act on the first night, which would then need 2 separate reminders. You could merge both reminders into one text box but you'd need the order numbers for both to appear in the circle (so the Spy for example would have a reminder circle that reads "0, 2" or something). Or you could code it to display 2 separate circles that each have their own hovers with their own tooltips. It's more work, but it's clearest.

Otherwise, only showing those on the Night Order sheet would, imo, be a fine compromise, since that should be pretty easy to implement.

**Comment by bra1n** [comment]
Agreed, this should be shown in some form, I just didn't get to it yet. 😅

**Comment by bra1n** [comment]
Demon/Minion info has been added to the night sheet. :-)
