### ISSUE TITLE
Feature request: Tooltips in the center of the screen

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#54]
I mostly use the app in vertical windows, because between the app, the reference sheet of the original game, and the Discord window, I have to split my screen to see everything at once. One problem that often shows up is that certain popups show outside of the screen, and the role/night tooltips are the biggest offenders since they show up on the sides of the role tokens.

To fix this, I think it'd be really good to have those tooltips show up in a box right in the middle of the screen. It'd be centered and nice looking, and it wouldn't risk going off-screen since it would dead center. It would also maybe make the tool usable on mobile, tho that's not the goal of this feature, so not something to really consider or test for.

**Comment by bra1n** [comment]
Hmm, this has already been in a ticket here: https://github.com/bra1n/townsquare/issues/28#issuecomment-653436543
I don't think there is a good solution for it, unfortunately, but I'll think some more about it.

**Comment by unrealed** [comment]
Regarding your comment in #28, could tooltip in the middle be an optional toggle? Because I understand the reasoning between having a link from the role toke/reminder circle to the textbox, but it would be nice to have it as an option, for those that DO use a vertical window. They'll probably understand it being optional since it's more of a edge case

**Comment by bra1n** [comment]
Ability tooltips now open on the inside of the circle, but half of the night tooltips don't. Not sure if I also want to force them to the inside, as that would overlap with the tokens itself. I could do it just for odd (ie. square) resolutions though...

**Comment by bra1n** [comment]
Due to some technical intricacies, this would take quite a bit more work than what would be gained from having the tooltips in the center, so I'll close it for now. The official app will have a lot of interface changes anyway, so I'll prefer to wait and see if something like this would be needed there at all.
