### ISSUE TITLE
Feature Request: Support Toy Maker

### ISSUE THREAD

**Issue by tanglebones** [bra1n/townsquare#55]
**Is your feature request related to a problem? Please describe.**
Better support for https://bloodontheclocktower.com/wiki/Toymaker games. Doesn't have to be general Fabled support. Right now 5/6 player games auto-hide the Demon bluffs and I can't see a way to get them back without adding more players.

**Describe the solution you'd like**
- Ability to leave the demon bluffs on in 5-6 player games
- Reminder token for demon has skipped their kill (optional, since a custom note works fine.)

**Describe alternatives you've considered**
If there is a way to get the bluffs to show in 5-6 player games and I missed it, my apologies. 

p.s. Thank you very much for making this tool!

**Comment by bra1n** [comment]
Incidentally, I've already been working on Fabled support and just pushed the changes to main. :-) I also enabled the bluff / additional character window to be shown for less than 7 players.
