### ISSUE TITLE
Feature Request: Game State Export

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#58]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a BotC stats site (for the time being just for my local group) to track win/losses, characters played etc. My initial design is quite laborious in terms of uploading the game state since you need to enter every player and character (as well as Demon bluffs etc). I think pretty much all of the game information is available in this online Grimoire and I'm wondering if the game information could be exported in a known data format that could be imported into a stats database

**Describe the solution you'd like**
The ability to export and download/view a JSON file containing the
- Players in the game (WIBNI if it included position in the circle)
- Role of each player
- Death state of each player
- Demon Bluffs
- The script played (preferably as a JSON document)
- WIBNI Alignment of each player

**Describe alternatives you've considered**
- Seeing as no information is stored in any central server an API query is out.
- I'm not planning on making my stats engine highly available so I think correspondingly a POST request rather than download is out.

**Additional context**
None

**Comment by bra1n** [comment]
Hey Geoff,
thanks for the detailed ticket! I can see how an easy export to JSON of a gamestate would be helpful for tools like yours. Alignment is something that is not tracked in the game, but to make up for it the export could contain all reminder tokens, including those that say "Evil" and "Good". Unfortunately I currently don't have a lot of time to work on this project and given that this is a feature request that won't be useful for most of our players, I'd rank it pretty low on the todo list. But I'll try to get around to add it in the future at some point. :-)

**Comment by bra1n** [comment]
Added in v2.0
