### ISSUE TITLE
Screenshot inconsistencies

### ISSUE THREAD

**Issue by daalta** [bra1n/townsquare#6]
I'm having some trouble with the screenshot feature - though feel free to delete my issue if I misunderstood how to use it 🎉

* Screenshots do not work on Firefox (nothing is copied to the clipboard)
* Screenshots for individual characters seem to be cropped incorrectly
  * ![image](https://user-images.githubusercontent.com/9169275/81397223-352b3e80-9127-11ea-993e-e9d7c6d79f3a.png)

**Comment by bra1n** [comment]
Were you using the browser zoom feature by chance? If you use browser-level zoom, there's no way (that I know of) for the scripts to figure out where exactly an element currently is, which is why you'll get screenshots that are off center.

**Comment by daalta** [comment]
Hmmm nope, 100% zoom! Latest Chrome version, dual monitor, 1080p, Windows 10

**Comment by bra1n** [comment]
And when you select the source for the browser stream, are you choosing the whole desktop, the browser window or the browser tab?

**Comment by daalta** [comment]
...Ooohh now I get it! I had it set to share the window, not the tab.

Thanks! Though it still doesn't work on Firefox. Probably because it's not possible to share individual tabs.

By the way, how's the screenshot feature intended to be used?

**Comment by bra1n** [comment]
Ah yeah, I need to implement a check for this, it's actually already on the todo list. :grimacing: 
The idea is that when you play on Discord, you quickly grab a screenshot of each player's role and send that to them. This saves you from having to type out everyone's role individually. The same goes for the screenshot of the town square / grimoire. When we play, every dusk and dawn there is a new screenshot posted to the chat by the storyteller for the players.

**Comment by daalta** [comment]
Ah so that's how you use it! I actually made a streaming setup just now, but posting the screenshots to Discord might be even better...
![firefox_2020-05-08_19-39-38](https://user-images.githubusercontent.com/9169275/81433177-6e35d400-9164-11ea-8dd6-8e2f06294a18.png)
