### ISSUE TITLE
Feature Request: Ability to add players in positions other than the end of the circle

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#61]
**Is your feature request related to a problem? Please describe.**
When Travellers are added to the game, they always have to be added to the end of the circle when you'd like to be able to put them in anywhere in the circle.

**Describe the solution you'd like**
The ability to add players into the circle at positions other than the end, or be able to move players within the circle and shuffle everyone else around.

**Describe alternatives you've considered**
I've listed some options above, I think the reasonable options are:
- Ability to add player to the left or right of an existing player.
- Ability to add a player to the end of the circle and then move them and push every other player/token round.

**Comment by bra1n** [comment]
Hi Geoff,

it is already possible to move players to different seats. Just click on the player name and then on "move player". So when you've added a traveler, you can seat them wherever you want.
