### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by xxKeefer** [bra1n/townsquare#65]
**Is your feature request related to a problem? Please describe.**

**We had a game were a bunch of new players to the game that were ghosts accidentally voted when they should not have. It swung the vote in a critical situation that left us feeling unsatisfied.**

**Describe the solution you'd like**

**I would like ghost players to have their vote token removed automatically after voting and then be barred from further votes.**

**Describe alternatives you've considered**

**Additional context**

**Comment by bra1n** [comment]
Hi Daniel,

thanks for the suggestion! Unfortunately, I think this feature would be outside the scope of this project. If I were to add game logic to voting, I would also have to consider special cases where ghost votes work differently, like Voudon or Beggar. This would be a lot of extra maintenance work, for which I don't have time. The tools offered here try to stay as close to a real grimoire/town square as possible, which means keeping track of (ghost) votes is still one of the responsibilities of the story teller.
