### ISSUE TITLE
BotC terminology: Hand up, and Vote

### ISSUE THREAD

**Issue by bignose-botc** [bra1n/townsquare#66]
The current Town Square vote symbology and terms do not match the Blood on the Clocktower game terminology.

* When taking a poll of players, the correct terminology is to “raise your hand” (or “hand up”). The skull, while charming, does not match this.

* When taking votes for a nomination, the correct terminology is to “vote” (approving the nomination) or do nothing. The “Vote No” and “Vote Yes” is confusingly different from the game terms.

**Expected behavior**

The terminology for all the polling of players should be:

* Approving the nomination is “vote”.
* The action to take for approving the nomination is “hand up” or “raise hand”.
* The raising of a hand should show a hand (not a skull), to match the in-person player action.
* Choosing not to vote should never be termed “vote” (rather, the correct term is “did not vote”).

**Comment by bra1n** [comment]
This will be fixed in v2.0, replacing the text on the vote buttons with "Hand UP" and "Hand DOWN" and cleaning up some related terminology.

**Comment by bignose-botc** [comment]
On 10-Dec-2020, Steffen wrote:

> This will be fixed in v2.0, replacing the text on the vote buttons
> with "Hand UP" and "Hand DOWN" and cleaning up some related
> terminology.

Great! That will resolve this issue.

If you like, I can work on a related change to the icons, to use hands
or something similar?

-- 
 \      “Holy priceless collection of Etruscan snoods, Batman!” —Robin |
  `\                                                                   |
_o__)                                                                  |
Ben Finney <ben@benfinney.id.au>

**Comment by bra1n** [comment]
Thanks, but I already took care of that as well. :-) 
![image](https://user-images.githubusercontent.com/325521/102093546-92a40e00-3e21-11eb-8839-d98a8a2f97c9.png)
