### ISSUE TITLE
Bug: There is only one kind of Balloonist reminder token

### ISSUE THREAD

**Issue by kamekura** [bra1n/townsquare#69]
**Describe the bug**
When the Balloonist is in play, we'd expect to see a distinct Balloonist reminder token for each character type (Townsfolk, Outsider, Minion, Demon, Traveler) in the reminders modal.
However, only one token is displayed.

Although this is a pre-release character for which there are no official rules currently, the unofficial Cobbler's Almanac indicates there should be a distinct token for each type: 
http://bignose.whitetree.org/projects/botc/diy/reference/cobblers-almanac.html#balloonist

This might be important in games where players can change character types (Pit-hag, Fang Gu). For example, if the Balloonist has seen the Pit-hag (as Minion) which then changes herself into a Demon, the Balloonist could potentially see her again (as Demon); besides, the Balloonist must not see another Minion again. A similar situation would happen if the Pit-hag transformed a Townsfolk into an Outsider.

Additionally, although the Lil Monsta rules aren't clear at the moment, a possible interpretation of its ability is that a Minion holding the LM token could register as both Minion and Demon, and so could be seen as either type (or both).

If the Balloonist tokens are identical, the Storyteller has to remember previous game state, which is undesirable.

**To Reproduce**
1. Add 7 players.
2. Go to the Characters Menu, click on 'Select Edition', then click on Custom Script/Characters and choose Catfishing.
3. Go to the Characters Menu, click on 'Choose & Assign', then choose any set of characters that includes the Balloonist, then click on "Assign 7 characters randomly".
4. Press G then click near any character token to add a reminder token.
5. Among the reminder tokens, a single Balloonist reminder token is displayed.

**Expected behavior**
When the Balloonist is in play, we'd expect to see one Balloonist reminder token for each character type in the reminders modal.

**Comment by bra1n** [comment]
Fixed in v2.0

**Comment by kamekura** [comment]
Thanks!

RAW the Balloonist would also potentially see a Traveler.  I don't think it makes much difference in practice unless the ST wants to be mean (showing a Traveler before showing all the other types) though...
