### ISSUE TITLE
Bug: Tokens going offscreen on mobile

### ISSUE THREAD

**Issue by Nextis-Plus** [bra1n/townsquare#70]
On certain mobile devices (most) the tokens are offscreen and in landscape mode are stacked on top of eachother.

1. Start the website on a mobile device
2. Add +3 players

Expected behavior :
Tokens are offscreen

**Comment by bra1n** [comment]
Did you try using the Zoom feature to reduce the token size? Due to the complexity of the game, anything smaller than a tablet isn't really supported, unfortunately.

**Comment by Nextis-Plus** [comment]
Hey,
What is this zoom method ? If you mean dezoom with two fingers that sadly doesn't work.

**Comment by bra1n** [comment]
![Bildschirmfoto 2020-12-14 um 22 18 03](https://user-images.githubusercontent.com/325521/102136869-4628f480-3e5a-11eb-965d-841ac47e53bd.png)
If you open the menu, in the first tab (Grimoire) you'll find the "Zoom" option with a magnifying glass. You can change the zoom level there.
