### ISSUE TITLE
Feature Request: Player Notes

### ISSUE THREAD

**Issue by prophetsfall** [bra1n/townsquare#71]
The custom note feature is awesome!

I would love to see an expanded feature where you can have notes associated with each player that you can review in a frame like the night order. If not that, maybe an expanded window that shows you all your notes? 
Currently if I have several they expand below the player, which makes the screen extra busy.

**Comment by bra1n** [comment]
Hey Patrick,
thanks for the suggestion. I can understand why you would want to have such a feature, but I'm not sure that it would be something that would fit the scope of this project. You can always take notes with another tool and the custom notes were mostly supposed to be small reminders that help you facilitate a smoother game experience for your players. If you feel the need to take longer individual notes, my suggestion would be to just use a notepad or text editor in that situation.
I'm not saying I might ever implement such a feature, but right now I think it's rather unlikely to be on the roadmap in the near future.

**Comment by bra1n** [comment]
After talking to TPI, this is not something that they / we want to be available directly in the app, for now.
