### ISSUE TITLE
Feature Request: Increased vote timer granularity

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#72]
**Is your feature request related to a problem? Please describe.**
I think there's a general opinion that 1 second for voting is too short a time but 2 seconds is too long, particularly with a large number of players. 

**Describe the solution you'd like**
Ideally a text field to set the vote timer to 1 decimal precision.

**Describe alternatives you've considered**
Other option would be to continue with step change but with smaller increments, 0.5, 0.25 or 0.1 seconds. I think 0.5 would be fine, I don't think more granular than that is required.

I think this is a relatively simple PR to change to 0.5 so happy to submit that if that's accepted.

**Comment by bra1n** [comment]
As chance would have it, for the upcoming v2.0 release I've already adjusted the vote timer steps down to 0.5 seconds. :-)
