### ISSUE TITLE
Bug: All players have to manually load the custom script JSON

### ISSUE THREAD

**Issue by lilserf** [bra1n/townsquare#75]
**Describe the bug**
Last week (18 Dec 2020) the Host could choose a custom script, the players could J to join as usual and see all the details.
This week (26 Dec 2020) all joining players get a popup alerting them that custom roles exist.
In order to correctly get into the game, the joining players have to hit "OK" on the warning popup, then choose Custom Script, then choose Enter URL and paste in the URL of the JSON file. It's an incredibly unfriendly user experience.

**To Reproduce**
Host a custom game.
On a separate client try to join the game.

**Expected behavior**
Joining players are shown the custom script without issue, as occurred a week ago.

**Additional context**

**Comment by bra1n** [comment]
Hi @lilserf,

thanks for the issue report. This has been an intentional change, as described in #60, #74 and the [CHANGELOG.md](https://github.com/bra1n/townsquare/blob/main/CHANGELOG.md#version-200). I'm planning to make this possible again, with custom images / icons disabled by default.

**Comment by lilserf** [comment]
Ah, I totally missed the CHANGELOG.md, sorry!
