### ISSUE TITLE
Feature Request: Leave Session hotkey

### ISSUE THREAD

**Issue by lilserf** [bra1n/townsquare#76]
**Is your feature request related to a problem? Please describe.**
Previously you could hit J to join a new session while already in one, but as of recent updates you have to Leave Session first

**Describe the solution you'd like**
A dedicated Leave hotkey would be nice so you can just `<L> <J>` to hop to a new game

**Describe alternatives you've considered**
Alternately just allow J to Join while already in a session

**Comment by bra1n** [comment]
Good idea, I'll remap the [J] button to "Leave session" when you're connected to a session.
