### ISSUE TITLE
Feature Request: Allow multiple instances of a character

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#77]
**Is your feature request related to a problem? Please describe.**
There are some custom scripts in existance which allow multiple instances of the same character to exist e.g. Double Brewing and Double Trouble. 
Currently, these scripts can be represented in JSON by re-creating the existing character's JSON with a new identity. While this is certainly workable, it's not particularly scalable and increases maintenance costs (since if night order or text ever changes, the JSON must be updated to reflect the actual role again). 

**Describe the solution you'd like**
The option to allow multiple instances of a character in a script. I think this could be represented by:
1. A new field in the JSON e.g. `max_instances`. By default this has a value of 1. Custom scripts could overwrite this value (I assume custom scripts can merge fields from base roles) to allow multiple instances
2. In the character selector, +/- buttons for each character token that can have multiple instances. The number of instances could be represented at the top. 

**Describe alternatives you've considered**
The only alternative I have considered in maintaining the current system of requiring the custom script JSON to repeat roles as required.

**Additional context**
![DoubleTroublev1 3](https://user-images.githubusercontent.com/3476614/103388409-cf9a2100-4b00-11eb-87d8-31ad5bf7f864.png)
Here's an example script that wishes to use multiple of each role.

**Comment by bra1n** [comment]
Hm, interesting concept. You can already assign the same character to more than one player. How exactly would you want a "duplicate" character to show up in addition to that? Twice on the reference sheet? Twice on the night order? Or just with a "x2" icon next to the token? Should a doubled character be assigned to two players in the character assignment tool?
I feel like this needs to be thought through first before I'm going to make any changes there...

**Comment by bra1n** [comment]
Apart from these questions, my proposition would be to support custom scripts like the following:
```json
[{"id": "empath"}, {"id": "empath"}, {"id": "bountyhunter"}, {"id": "bountyhunter"}]
```
...which would be a script with 2 Empaths and 2 Bounty Hunters.

**Comment by AdmiralGT** [comment]
> Hm, interesting concept. You can already assign the same character to more than one player. How exactly would you want a "duplicate" character to show up in addition to that? Twice on the reference sheet? Twice on the night order? Or just with a "x2" icon next to the token? Should a doubled character be assigned to two players in the character assignment tool?
I feel like this needs to be thought through first before I'm going to make any changes there...

I didn't realise as the host you could assign multiple players to the same role. I thought role assignement was unique and therefore required the additional roles in the JSON.

I think the biggest hurdle to this currently is the "Choose and Assign" UI.
![image](https://user-images.githubusercontent.com/3476614/103469992-16d41c00-4d64-11eb-92d0-33901147d7f1.png)

With the current framework that's possible in two ways:
1. Duplicate the character in the JSON so two tokens appear (which requires maintenance/updates any time changes are made)
2. Use a replacement character in the JSON and then replace that once roles have been assigned. These don't actually require any definitions since they'll be replaced by actual character tokens (but as ST you need to create a mapping from replacement token to real role)

Ideally I would like this to be able to allocate multiple instances of the same role without duplicating tokens in the "Choose and Assign" view and instead just let me increment/decrement and it show me how many are going to be created/assigned. A nice addition would be if that could be controlled by a character/script option in the JSON.

On duplicating IDs in the JSON, does this work for custom characters? Can I define a custom character and then reference it again with just the ID?

```
[
    {
        "id": "custom_char",
        "name": "My awesome character",
        "ability": "My awesome ability",
        "firstNight": 0,
        "firstNightReminder": "",
        "otherNight" : 0,
        "otherNightReminder": "",
        "team": "townsfolk"
    },
    {
        "id": "custom_char"
    }
```

**Comment by bra1n** [comment]
So, if I understand this right, the two major issues here are the script JSON maintenance (which would be eliminated by [my suggestion](https://github.com/bra1n/townsquare/issues/77#issuecomment-753130468)) and the role assignment window?
I could adjust it so that when a custom script contains duplicates of a character, those duplicates will show up in the assignment window, too. Would that help?
As for homebrew / custom characters: there isn't going to be support for referencing previously defined characters. You'll just have to define them twice, I'm afraid.

**Comment by AdmiralGT** [comment]
I think I'm going to close this issue. I think the ability to already assign multiple characters means just using simple replacement characters is sufficient to deal with this and I think without strict control over that means this isn't particularly useful so isn't worthwhile doing anything.

**Comment by AdmiralGT** [comment]
I think we should reopen this issue. Legion doesn't really work well with the tool currently as if you randomise roles, the first n players (where n is the number of good tokens + 1 legion token) get assigned the roles (see the recent megastream for an instance of this). I think there needs to be a way to set # of legion tokens in the game.

**Comment by bra1n** [comment]
Alright, I'll add a way to assign the same character multiple times in the character selection popup. 👍

**Comment by bra1n** [comment]
Added with 2.7.0
