### ISSUE TITLE
Character selection screen: Display name instead of number

### ISSUE THREAD

**Issue by daalta** [bra1n/townsquare#8]
(This is a suggestion)
The character selection screen currently displays the player's number instead of their name.

![firefox_2020-05-08_12-57-07](https://user-images.githubusercontent.com/9169275/81399634-9f45e280-912b-11ea-8c5a-af313b128b90.png)

It would probably be easier to see what player you're assigning if their name was visible on this screen, too.

**Comment by bra1n** [comment]
Ha, this was actually some debugging output that I forgot to remove, but good idea nonetheless!
I'll add it.
