### ISSUE TITLE
Feature Request: Improved clarity of vote history

### ISSUE THREAD

**Issue by lilserf** [bra1n/townsquare#82]
**Is your feature request related to a problem? Please describe.**
When referring to the vote history popup, it's easy at a glance to see the Majority number for a given vote and think that it's the vote total for that vote. As a separate column it stands out more than the number next to the "people" icon and names.

I'm honestly not sure if the "Majority" number as a stand-alone number is even that useful. I'd prefer a quick-glance checkmark or X to denote whether this vote *achieved* a majority - I rarely need to know after-the-fact what the majority threshold was for a particular vote.

**Describe the solution you'd like**
Some options:
- Move the majority column away from the "Hand up" column
- Make the total vote number more prominent as its own column or combine it with majority as "5 / 6" or "8 / 6" etc
- Add an easy-to-read "did this vote pass or not" indicator (check or x or similar)

**Additional context**
I may try to put together a PR for this :)
![image](https://user-images.githubusercontent.com/151635/103553736-dcf63900-4e7b-11eb-9885-79fdd5a16773.png)

**Comment by JulGvoz** [comment]
![image](https://user-images.githubusercontent.com/46909274/103556807-fc608680-4eba-11eb-8a0b-678d311d6bfa.png)
would implementation looking like this work?

**Comment by lilserf** [comment]
Yeah, I think that would definitely be clearer.

**Comment by bra1n** [comment]
Good idea! However, if you drop the "majority" label, it's much less clear then what exactly the number after the slash means. People would look at "Votes 4/3" and wonder what it means. Any idea how to communicate that better?

**Comment by JulGvoz** [comment]
I thought about having the header show "Votes / Majority", but that makes the column wider than necessary. Perhaps add a footnote or give a detailed explanation when hovering over with a mouse?

**Comment by bra1n** [comment]
Let's continue this discussion in the PR

> I thought about having the header show "Votes / Majority", but that makes the column wider than necessary. Perhaps add a footnote or give a detailed explanation when hovering over with a mouse?

Maybe we should continue this discussion in the PR... ;-)
