### ISSUE TITLE
Bug: It is not possible for dead players to vote to join cults or exile travelers

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#84]
**Describe the bug**
There are 3 types of votes that can actually occur in game
1. Nominating a player for execution
2. Asking to form a cult
3. Nominating a traveler for exile

The online grimoire only allows players to vote if they have a dead vote. Dead votes are only applicable to "nominating a player for execution" so if a player has used their vote, they're not able to vote for the other forms of votes.

**To Reproduce**
1. Kill a player
2. Remove their dead vote
3. Create a "Cult Leader" vote or nomination to exile a traveler. The dead players are unable to vote.

**Expected behavior**
Dead players should be able to vote.

**Additional context**
I think the problem here is to allow another form of vote separate from nomination, that allows all players, regardless of dead state to vote.

**Comment by bra1n** [comment]
It seems I'm unable to reproduce the "dead player without a vote can't vote on a traveler nomination" part of the issue:
![Bildschirmfoto 2021-01-06 um 21 48 17](https://user-images.githubusercontent.com/325521/103818540-02946580-5069-11eb-8209-0ce63b2d7699.png)
Do you have a game state JSON of a game where this happened so that I can reproduce it? Or at least a screenshot and a live session channel name?
As for Cult Leader vote: this is a known shortcoming, as generic votes for everyone are not supported by the tool yet. It's on the roadmap, but since the almanac for Cult Leader isn't public yet, I'd suggest you simply give everyone their vote token back temporarily in case of a Cult Leader vote.

**Comment by AdmiralGT** [comment]
I don't have a game state, I just assumed that from Cult Leader. However, it needs to be possible for you to vote on a traveler without dead votes (since you can also nominate a traveler for execution which needs to not use dead votes).

**Comment by bra1n** [comment]
> I don't have a game state, I just assumed that from Cult Leader. However, it needs to be possible for you to vote on a traveler without dead votes (since you can also nominate a traveler for execution which needs to not use dead votes).

That is possible and I just tested it, as can be seen in the screenshot above. Maybe there was a specific circumstance that lead to a bug? Hence me asking for logs or a screenshot or a game state JSON.

**Comment by AdmiralGT** [comment]
Sorry, I meant it needs to be possible to vote on a travler without being allowed to use dead votes. In the case where you are nominating the traveler for execution, dead votes do count. You can nominate a travler for exile (which you need to be able to do without a dead vote) and you can nominate a travler for execution (which requires a dead vote).

**Comment by bra1n** [comment]
I'm not sure I understand. What exactly is broken in this regard? Nomination works independently of current player status (dead / alive / voteless) and voting on banishing travellers also works when you don't have a vote token anymore.

**Comment by AdmiralGT** [comment]
![image](https://user-images.githubusercontent.com/3476614/103890060-56419600-50df-11eb-894f-a85c96f38cff.png)
![image](https://user-images.githubusercontent.com/3476614/103890135-6f4a4700-50df-11eb-9fad-35dddb2b2969.png)

There is only a single "Nomination" ability but Travelers can be nominated for 2 different reasons

1. You can nominate a traveler for Exile. All players can vote on this, regardless of their dead status
2. You can nominate a traveler for Execution. Only players with votes can vote on this, so if you have used your dead vote, you cannot vote.

Currently you can only do the first of these (because all dead players can vote when a traveler is nominated).

**Comment by bra1n** [comment]
Aah, now we're getting somewhere! 😁  The issue here is that your number 2 is not allowed by the game rules, so it is not supported by the tool. A traveler can't be nominated for an execution, only for exile.

**Comment by AdmiralGT** [comment]
Indeed! I'm sure I've played in games or seen games played where Travelers have been nominated for execution as opposed to exile (for Zombuul/Vortox style things) so I presumed that was the rules. Reading https://drive.google.com/file/d/1jb3SIsEka2GV-stS-c3KDt-ZycPjwr9o/view it would suggest you can't do it though. So I think the only issue is with Cult Leader which is on the roadmap so I'll close this.

**Comment by bra1n** [comment]
Yeah, it's a pretty easy mistake to make and I've also played (and ST'ed) plenty of games where this happened, before I learned of this rule. Unfortunately, the rulebook is also not very straight forward about it, so I can see where the confusion stems from.
