### ISSUE TITLE
Bug: Black triangle next to player seating button is offset in weirdly sized browser windows

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#88]
**Describe the bug**
Black arrow/triangle next to the "Seat occupied" label (and presumably other similar labels) is incorrectly offset when browser is scaled weird.

**To Reproduce**
1. Join a game with many players
2. Click on a player's name
3. Resize the browser window
4. See the problem

**Expected behavior**
The triangle should be correctly aligned, instead of drifting upwards

**Screenshots**
![image](https://user-images.githubusercontent.com/46909274/104069865-4379af00-520e-11eb-9780-33e60e87e6c5.png)
![image](https://user-images.githubusercontent.com/46909274/104069956-758b1100-520e-11eb-9cc0-63f183a84abe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Developer Edition
 - Version 85.0b5 (64-bit)

**Comment by bra1n** [comment]
Great issue report! I'll fix it ASAP. 😃
