### ISSUE TITLE
Feature Request: Vote History - Option controlled by Host

### ISSUE THREAD

**Issue by LukeC82** [bra1n/townsquare#89]
**Is your feature request related to a problem? Please describe.**
I think the new Vote History should be controlled by the ST - i.e.: it's availability for the town is toggled by the current sessions host.

Perfect recall of voting history should require some effort from the town, at the discretion of the player group and/or ST.

**Describe the solution you'd like**
A toggle for the Vote History's availability for the town, controlled by the host.

**Describe alternatives you've considered**
Vote History is excellent for players groups that agree the task of tracking online noms/votes is unnecessary online.
However, where there is some disagreement or you group simply decides it's too much free information, host/ST should have control.

**Additional context**

**Comment by bra1n** [comment]
@LukeC82 I know it's not really well documented or obvious, but when the Storyteller clears the vote history, it will be cleared for every other player, too. I'd suggest you clear it at the end of each day.
