### ISSUE TITLE
Feature Request: Hotkey/Convenient button for Night phase

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#90]
**Is your feature request related to a problem? Please describe.**
Storytellers often forget to turn on the night, and it is often fiddly to toggle it (can take multiple seconds for something that should usually take only a moment?)

**Describe the solution you'd like**
Either a button in the middle (since ST never votes, which means the button won't be obstructed), or simply a hotkey (or both)

**Comment by bra1n** [comment]
I think the center of the circle is already very crowded and doesn't really have enough space for an extra button. And the N hotkey is already bound to the night order sheet. This is also the first time I've heard about this being an issue, especially given that you're switching to night at most half a dozen times over a span of something like 2 hours... 🤔

**Comment by magroader** [comment]
S for Switch seems good to me

**Comment by bra1n** [comment]
Looks like there seems to be enough demand to add this. 👍

**Comment by bra1n** [comment]
@JulGvoz or @davotronic5000 - maybe one of you wants to work on this? It should be an easy change. 🙂

**Comment by davotronic5000** [comment]
Sure, I can put a PR up for this shortly,  thinking about setting "p" as the hotkey for phase as "n" is already assigned to the night sheet.

**Comment by bra1n** [comment]
Maybe S as in "Switch"?

**Comment by bra1n** [comment]
Added by @davotronic5000
