### ISSUE TITLE
Feature Request: Update character icons for LuF characters + Lycanthrope icon

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#92]
**Is your feature request related to a problem? Please describe.**
New icons for Lycanthrope, Amnesiac, Widow, Leviathan, Goblin and Fisherman have been uploaded. It would be 

**Describe the solution you'd like**
High quality images (at the very least, comparable to other characters) being uploaded.

**Describe alternatives you've considered**
It is also possible to try to attempt to recreate the icons to the best of our ability.

**Additional context**
In the unofficial discord: https://discord.com/channels/569683781800296501/570050401315979305/799483594464559164
![image](https://user-images.githubusercontent.com/46909274/104851735-7d7a3d80-58ff-11eb-825d-b476e16233e8.png)
![image](https://user-images.githubusercontent.com/46909274/104851739-80752e00-58ff-11eb-8d7c-5d27692288f1.png)
![image](https://user-images.githubusercontent.com/46909274/104851740-81a65b00-58ff-11eb-8c20-52161eebd95c.png)
![image](https://user-images.githubusercontent.com/46909274/104851743-83701e80-58ff-11eb-9b11-cbd56dcd1bda.png)
![image](https://user-images.githubusercontent.com/46909274/104851744-85d27880-58ff-11eb-8483-62863dcd653a.png)
![image](https://user-images.githubusercontent.com/46909274/104851789-bca88e80-58ff-11eb-9c17-99d0fc21a00b.png)

**Comment by bra1n** [comment]
Unfortunately, those are too small to use them directly. I'd need them in a size similar to this: https://github.com/bra1n/townsquare/blob/main/src/assets/icons/amnesiac.png

**Comment by bra1n** [comment]
By the way, the Lycanthrope icon should already be up-to-date, not sure why you included it in the list?

**Comment by JulGvoz** [comment]
![image](https://user-images.githubusercontent.com/46909274/104886323-37aa8d00-5972-11eb-90fd-c455a63baa86.png)
![image](https://user-images.githubusercontent.com/46909274/104886325-3a0ce700-5972-11eb-9ede-d8e2e5de0c54.png)
Comparing the images, it is pretty clear that they don't match what has been uploaded in the unofficial, by I presume more official source (as the current Lyconthrope icon in the tool has been made by @AWConant I assume)

**Comment by JulGvoz** [comment]
![image](https://user-images.githubusercontent.com/46909274/105573885-4e355780-5d69-11eb-92b4-cd3ce71024ed.png)
This could be more suitable for Amnesiac

**Comment by bra1n** [comment]
Thanks, added it. 👍

**Comment by bra1n** [comment]
> Comparing the images, it is pretty clear that they don't match what has been uploaded in the unofficial, by I presume more official source (as the current Lyconthrope icon in the tool has been made by @AWConant I assume)

Personally, I think they're close enough. ;-) I'll probably have to give all these icons another pass when the game is officially released.

**Comment by bra1n** [comment]
I'm going to close this, given that the final icons are soon to be released and then this ticket will be moot. 🙂
