### ISSUE TITLE
Feature Request: Partially revert #75 by prompting players

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#93]
**Is your feature request related to a problem? Please describe.**
Many are confused by the change, and has become quite difficult to play homebrews.

**Describe the solution you'd like**
When a player attempts to join a game where custom assets are used, a modal would pop up, describing the danger and issues with custom assets. The player could then press a button to still use the homebrew script with assets.

**Describe alternatives you've considered**
Perhaps simply allowing players to load in the script *after* they join in other ways, even manually, could be a temporary solution

**Comment by bra1n** [comment]
The security concerns are only half of the reason that this feature has been disabled for now. The other half is the traffic demand for syncing full homebrew scripts to other players. Both of these are already on the roadmap and I'll work on them as soon as I have a bit more time for this. Check #74 or the project tabs if you want to keep track of it. :-)

**Comment by JulGvoz** [comment]
Hmm, I feel like exposing IP addresses of the players to the Storyteller (and the reverse) could be... unsettling.
Would it be possible to instead work on some kind of hosting methods? For example, setting up a separate repository with many of the json files from scripts and some kind of automation. The players would then GET the script from the link which back-end would send to them. Thus the payload is reduced to a simple link, possibly just an id.

**Comment by bra1n** [comment]
> Hmm, I feel like exposing IP addresses of the players to the Storyteller (and the reverse) could be... unsettling.

Which is exactly why I had to remove live session homebrew support for the time being.

> Would it be possible to instead work on some kind of hosting methods? For example, setting up a separate repository with many of the json files from scripts and some kind of automation. The players would then GET the script from the link which back-end would send to them. Thus the payload is reduced to a simple link, possibly just an id.

Possible? Absolutely! But what you described would be so much out of scope of this website, that you could probably create your own project just for this idea. 😄  Let me know if you do, then I can add it to a whitelist of allowed homebrews in live sessions.
