### ISSUE TITLE
Feature Request: Parse link when joining

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#94]
**Is your feature request related to a problem? Please describe.**
When joining a game, pasting the entire link, for example `https://clocktower.online/#4251` in the join prompt doesn't join the game 4251.

**Describe the solution you'd like**
It would be quite easy to simply match if the code entered is simply a link, and that could be automatically parsed.

**Comment by bra1n** [comment]
Does this... happen often? This is the first time I hear about it. 🤔  I guess it would be rather easy to implement, but is it really something that would help a lot of people?

**Comment by bra1n** [comment]
@JulGvoz maybe do you want to give it a try yourself? It shouldn't be too hard to implement.
