### ISSUE TITLE
Bug: Error when getting an out-of-script character sent to you

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#95]
**Describe the bug**
If the host sends you, the player, a character that is not in the script, you won't see the icon, you won't be able to change your own character, and you won't be able to load Game State JSON

**To Reproduce**
1. Host a game
2. Set script to TB
3. Add a few players
4. Set the players to TB character
5. Join that game (through another computer or browser)
6. Click claim seat
7. Back at host: send characters
8. Back at player: click on your own empty token, observe console too

**Expected behavior**
For characters defined in roles.json, the role should be sent. For undefined characters, possibly nothing should be set on the players side, or a custom character without assets should be set.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Developmer Edition
 - Version 85.0b9 (64-bit)

**Comment by bra1n** [comment]
Ah, nice find. I agree that receiving a character that is not part of the current edition should not mess up your local game. I'll fix it! 👍

**Comment by bra1n** [comment]
Should be fixed now.
